//! Schema-level Lisp emission — one `(defteia-schema …)` per `IacResource`.

use iac_forge::ir::{IacAttribute, IacProvider, IacResource, IacType};

/// Render a single `IacResource` as a `(defteia-schema …)` form.
///
/// The form describes the *type* of the resource (what attributes exist,
/// which are required, which are output-only); end users author concrete
/// instances with `(defteia :tipo … :nome … :atributos …)`.
#[must_use]
pub fn emit_resource_lisp(resource: &IacResource, provider: &IacProvider) -> String {
    let tipo = format!("{}/{}", provider.name, kebab(&resource.name));
    let mut out = String::new();
    out.push_str(";; Auto-generated by caixa-teia-forge. Do not edit by hand.\n\n");
    out.push_str("(defteia-schema\n");
    out.push_str(&format!("  :tipo     {tipo}\n"));
    if !resource.description.is_empty() {
        out.push_str(&format!("  :descricao {:?}\n", resource.description));
    }
    out.push_str("  :atributos (\n");
    for attr in &resource.attributes {
        out.push_str("    ");
        out.push_str(&emit_attribute(attr));
        out.push('\n');
    }
    out.push_str("  ))\n");
    out
}

fn emit_attribute(attr: &IacAttribute) -> String {
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!(":nome {:?}", attr.canonical_name));
    parts.push(format!(":tipo {}", emit_type(&attr.iac_type)));
    if attr.required {
        parts.push(":obrigatorio #t".into());
    }
    if attr.computed {
        parts.push(":computado #t".into());
    }
    if attr.sensitive {
        parts.push(":sensivel #t".into());
    }
    if attr.immutable {
        parts.push(":imutavel #t".into());
    }
    if !attr.description.is_empty() {
        parts.push(format!(":descricao {:?}", attr.description));
    }
    format!("({})", parts.join(" "))
}

#[allow(clippy::match_same_arms)]
fn emit_type(t: &IacType) -> String {
    match t {
        IacType::String => "String".into(),
        IacType::Integer => "Integer".into(),
        IacType::Float => "Float".into(),
        IacType::Numeric => "Numeric".into(),
        IacType::Boolean => "Boolean".into(),
        IacType::List(inner) => format!("(List {})", emit_type(inner)),
        IacType::Set(inner) => format!("(Set {})", emit_type(inner)),
        IacType::Map(inner) => format!("(Map {})", emit_type(inner)),
        IacType::Object { name, .. } => format!("(Object :nome {name:?})"),
        IacType::Enum { values, .. } => {
            let vs = values
                .iter()
                .map(|v| format!("{v:?}"))
                .collect::<Vec<_>>()
                .join(" ");
            format!("(Enum {vs})")
        }
        IacType::Any => "Any".into(),
        _ => "Any".into(), // IacType is #[non_exhaustive]
    }
}

fn kebab(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('-');
            }
            for lc in c.to_lowercase() {
                out.push(lc);
            }
        } else if c == '_' {
            out.push('-');
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use iac_forge::ir::IacType;
    use iac_forge::testing::{TestAttributeBuilder, test_provider, test_resource};

    fn vpc_resource() -> iac_forge::ir::IacResource {
        let mut r = test_resource("vpc");
        r.description = "A VPC.".into();
        r.attributes = vec![
            TestAttributeBuilder::new("cidr-block", IacType::String)
                .required()
                .description("CIDR")
                .build(),
        ];
        r
    }

    #[test]
    fn emits_schema_with_required_attr() {
        let src = emit_resource_lisp(&vpc_resource(), &test_provider("aws"));
        assert!(src.contains("defteia-schema"));
        assert!(src.contains("aws/vpc"));
        assert!(src.contains(":obrigatorio #t"));
        assert!(src.contains(":nome \"cidr_block\""));
    }
}
