//! `caixa-teia-forge` — iac-forge backend that emits tatara-lisp caixas.
//!
//! Parallel to `pangea-forge` (Ruby emission) and `terraform-forge` (Go
//! provider emission). One IacResource in, one `(defteia …)` out, rolled
//! up into a full caixa (lib/<nome>.lisp + caixa.lisp).
//!
//! Example output for `IacResource { name: "aws_vpc", attributes: [cidr_block, tags] }`:
//!
//! ```lisp
//! ;; Auto-generated by caixa-teia-forge from the AWS OpenAPI spec.
//! ;; Do not edit by hand.
//!
//! (defteia-schema
//!   :tipo aws/vpc
//!   :atributos ((:nome "cidr-block" :tipo String :obrigatorio #t)
//!               (:nome "tags"       :tipo Object)))
//! ```
//!
//! Consumers then author concrete instances with the same `(defteia …)`
//! surface caixa-teia parses — same IR, two sources (hand-rolled vs
//! generated schema).

pub mod backend;
pub mod emit;
pub mod naming;

pub use backend::LispBackend;
pub use emit::emit_resource_lisp;
pub use naming::LispNaming;
