apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "caixa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "caixa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "caixa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "caixa.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "caixa.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: caixa-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --log={{ .Values.logFormat }}
            {{- with .Values.watchNamespace }}
            - --namespace={{ . }}
            {{- end }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cache
              mountPath: /var/cache/caixa
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
