// SPDX-License-Identifier: MIT
//! `caixa-core` — manifest types, layout invariants, and version contract
//! for the caixa tatara-lisp package system.
//!
//! The `caixa.lisp` manifest is itself a [`tatara_lisp::domain::TataraDomain`]
//! — parsing is the derive macro, which makes ill-typed manifests impossible
//! at load time (the same discipline Cargo gets from `Cargo.toml`, but
//! enforced by Rust types rather than TOML schema).
//!
//! Layout invariants (lib/ presence, exe/ population, service entries) are
//! enforced by [`LayoutInvariants`], run by `caixa-feira` before any build
//! step.

extern crate self as caixa_core;

pub mod aplicacao;
pub mod behavior;
pub mod dep;
pub mod dialeto;
pub mod kind;
pub mod layout;
pub mod limits;
pub mod manifest;
pub mod render;
pub mod supervisor;
pub mod upgrade;
pub mod version;

pub use aplicacao::{
    AplicacaoError, AplicacaoSpec, CircuitBreaker, DEFAULT_SERVICO_PORT, Entrada, Membro,
    MeshPolicy, POLICY_BREAKER_MAX_FAILURES_MAX, POLICY_BREAKER_WINDOW_MAX, POLICY_RATE_LIMIT_MAX,
    POLICY_RETRIES_MAX, POLICY_TIMEOUT_MAX, Placement, PlacementStrategy, RateLimit, RateLimitUnit,
    SERVICO_PORT_MIN, WitContract, WitTarget,
};
pub use behavior::{BehaviorError, BehaviorSpec};
pub use dep::{Dep, DepError, DepList, DepSource};
pub use dialeto::{CaixaDialeto, DialetoError, classify as classify_dialeto};
pub use kind::CaixaKind;
pub use layout::{LayoutError, LayoutInvariants, StandardLayout};
pub use limits::{
    LIMITS_CPU_MILLICORES_MAX, LIMITS_FUEL_MAX, LIMITS_MEMORY_WASM32_MAX_BYTES,
    LIMITS_MEMORY_WASM32_PAGE_BYTES, LIMITS_WALL_CLOCK_MAX, LimitsError, LimitsSpec,
};
pub use manifest::{Caixa, LeituraError, ManifestError};
pub use render::{
    CAIXA_KEY_DEPS, CAIXA_KEY_DEPS_DEV, CAIXA_KIND_LABEL_ACAO, CAIXA_KIND_LABEL_APLICACAO,
    CAIXA_KIND_LABEL_BIBLIOTECA, CAIXA_KIND_LABEL_BINARIO, CAIXA_KIND_LABEL_SERVICO,
    CAIXA_KIND_LABEL_SUPERVISOR, CARGO_FEATURE_NAME_MAX_LEN, CILIUM_API_VERSION,
    CILIUM_AUTH_MODE_DISABLED, CILIUM_AUTH_MODE_REQUIRED, CILIUM_KEY_AUTHENTICATION,
    CILIUM_KEY_ENDPOINT_SELECTOR, CILIUM_KEY_FROM_ENDPOINTS, CILIUM_KEY_HTTP, CILIUM_KEY_INGRESS,
    CILIUM_KEY_MODE, CILIUM_KEY_PATH, CILIUM_KEY_PORTS, CILIUM_KEY_TO_PORTS,
    CILIUM_KIND_NETWORK_POLICY, CIRCUIT_BREAKER_KEY_MAX_FAILURES, CIRCUIT_BREAKER_KEY_WINDOW,
    CLUSTER_BUNDLE_LAREIRA_ENABLED_DEFAULT, COMPUTEUNIT_MODULE_KEY_SOURCE,
    COMPUTEUNIT_SPEC_KEY_CAPABILITIES, COMPUTEUNIT_SPEC_KEY_MODULE, COMPUTEUNIT_SPEC_KEY_TRIGGER,
    COMPUTEUNIT_YAML_SUFFIX, CONTRATO_EDGE_LABEL_SEPARATOR, CONTRATO_KEY_DE, CONTRATO_KEY_PARA,
    CONTRATO_KEY_WIT, CiDecomposeFailure, DEFAULT_FLUX_CHART_SOURCE_SUBPATH,
    DEFAULT_FLUX_KUSTOMIZATION_TIMEOUT, DEFAULT_FLUX_RECONCILE_INTERVAL,
    DEFAULT_FLUX_SYSTEM_NAMESPACE, DEFAULT_GATEWAY_CLASS_NAME, DEFAULT_LIBRARY_NAME,
    DEFAULT_NAMESPACE, DEP_AUTHOR_KEY_DEPS, DEP_AUTHOR_KEY_DEPS_DEV, DEP_SOURCE_KEY_TIPO,
    DEP_SOURCE_TIPO_GIT, DEP_SOURCE_TIPO_PATH, DNS_1123_LABEL_MAX_LEN, ENTRADA_KEY_HOST,
    ENTRADA_KEY_PARA, ENTRADA_KEY_PATHS, ENTRADA_KEY_PORT, FLEET_PROGRAMS_KEY_APLICACAO,
    FLEET_PROGRAMS_KEY_NAME, FLEET_PROGRAMS_KEY_PROGRAMS, FLEET_PROGRAMS_KEY_VERSAO,
    FLUX_GITREPOSITORY_API_VERSION, FLUX_GITREPOSITORY_KEY_REF, FLUX_GITREPOSITORY_KEY_URL,
    FLUX_GITREPOSITORY_REF_KEY_BRANCH, FLUX_GITREPOSITORY_REF_KEY_COMMIT,
    FLUX_GITREPOSITORY_REF_KEY_TAG, FLUX_GITREPOSITORY_YAML_FILENAME,
    FLUX_HELMCHART_TEMPLATE_KEY_CHART, FLUX_HELMRELEASE_API_VERSION,
    FLUX_HELMRELEASE_CREATE_NAMESPACE_DEFAULT, FLUX_HELMRELEASE_KEY_CREATE_NAMESPACE,
    FLUX_HELMRELEASE_KEY_INSTALL, FLUX_HELMRELEASE_KEY_REMEDIATE_LAST_FAILURE,
    FLUX_HELMRELEASE_KEY_REMEDIATION, FLUX_HELMRELEASE_KEY_RETRIES, FLUX_HELMRELEASE_KEY_UPGRADE,
    FLUX_HELMRELEASE_REMEDIATE_LAST_FAILURE_DEFAULT, FLUX_HELMRELEASE_REMEDIATION_RETRIES_DEFAULT,
    FLUX_HELMRELEASE_YAML_FILENAME, FLUX_KEY_CHART, FLUX_KEY_HEALTH_CHECKS, FLUX_KEY_INTERVAL,
    FLUX_KEY_SOURCE_REF, FLUX_KEY_VALUES, FLUX_KIND_GIT_REPOSITORY, FLUX_KIND_HELM_RELEASE,
    FLUX_KIND_KUSTOMIZATION, FLUX_KUSTOMIZATION_API_VERSION, FLUX_KUSTOMIZATION_KEY_PATH,
    FLUX_KUSTOMIZATION_KEY_PRUNE, FLUX_KUSTOMIZATION_KEY_TIMEOUT, FLUX_KUSTOMIZATION_PRUNE_DEFAULT,
    FLUX_KUSTOMIZATION_YAML_FILENAME, GATEWAY_API_API_VERSION,
    GATEWAY_API_DEFAULT_HTTP_LISTENER_NAME, GATEWAY_API_DEFAULT_HTTP_LISTENER_PORT,
    GATEWAY_API_DEFAULT_HTTP_ROUTE_PATH, GATEWAY_API_HOSTNAME_MAX_LEN,
    GATEWAY_API_HTTP_PATH_MAX_LEN, GATEWAY_API_KEY_ATTEMPTS, GATEWAY_API_KEY_BACKEND_REFS,
    GATEWAY_API_KEY_GATEWAY_CLASS_NAME, GATEWAY_API_KEY_HOSTNAME, GATEWAY_API_KEY_HOSTNAMES,
    GATEWAY_API_KEY_LISTENERS, GATEWAY_API_KEY_MATCHES, GATEWAY_API_KEY_NAME,
    GATEWAY_API_KEY_PARENT_REFS, GATEWAY_API_KEY_PATH, GATEWAY_API_KEY_REQUEST,
    GATEWAY_API_KEY_RETRY, GATEWAY_API_KEY_SECTION_NAME, GATEWAY_API_KEY_TIMEOUTS,
    GATEWAY_API_KEY_VALUE, GATEWAY_API_KIND_GATEWAY, GATEWAY_API_KIND_HTTP_ROUTE,
    GATEWAY_API_PATH_MATCH_TYPE_PATH_PREFIX, GATEWAY_API_PROTOCOL_HTTP, GIT_OID_SHA1_LEN,
    GIT_OID_SHA256_LEN, GIT_REF_NAME_MAX_LEN, GIT_REPO_URL_MAX_LEN, HELM_CHART_API_VERSION,
    HELM_CHART_DEPENDENCY_KEY_ALIAS, HELM_CHART_DEPENDENCY_KEY_NAME,
    HELM_CHART_DEPENDENCY_KEY_REPOSITORY, HELM_CHART_DEPENDENCY_KEY_VERSION,
    HELM_CHART_KEY_API_VERSION, HELM_CHART_KEY_APP_VERSION, HELM_CHART_KEY_DEPENDENCIES,
    HELM_CHART_KEY_TYPE, HELM_CHART_README_FILENAME, HELM_CHART_TYPE_APPLICATION,
    HELM_CHART_TYPE_LIBRARY, HELM_CHART_YAML_FILENAME, HELM_VALUES_KEY_ENABLED,
    HELM_VALUES_YAML_FILENAME, KUBE_KEY_API_VERSION, KUBE_KEY_KIND, KUBE_KEY_LABELS,
    KUBE_KEY_MATCH_LABELS, KUBE_KEY_METADATA, KUBE_KEY_NAME, KUBE_KEY_NAMESPACE, KUBE_KEY_PORT,
    KUBE_KEY_PROTOCOL, KUBE_KEY_RULES, KUBE_KEY_SPEC, KUBE_KEY_TYPE, KUBE_PROTOCOL_TCP,
    KindMismatch, LABEL_APLICACAO, LABEL_CONTRATO, LABEL_PROGRAM, LAREIRA_CHART_KEYWORDS,
    LAREIRA_CHART_NAME_NOME_MAX_LEN, LAREIRA_CHART_NAME_PREFIX, LAYOUT_DIR_EXE, LAYOUT_DIR_LIB,
    LAYOUT_DIR_SERVICOS, LAYOUT_MISSING_ENTRY_KIND_BEHAVIOR_CALLBACK,
    LAYOUT_MISSING_ENTRY_KIND_BIBLIOTECA, LAYOUT_MISSING_ENTRY_KIND_EXE,
    LAYOUT_MISSING_ENTRY_KIND_SERVICO, LAYOUT_MISSING_ENTRY_KIND_UPGRADE_SCRIPT,
    LISP_SOURCE_EXTENSION, M2_AUTHOR_KEY_BEHAVIOR, M2_AUTHOR_KEY_LIMITS,
    M2_AUTHOR_KEY_UPGRADE_FROM, M2_BEHAVIOR_AUTHOR_KEY_ON_CALL, M2_BEHAVIOR_AUTHOR_KEY_ON_CAST,
    M2_BEHAVIOR_AUTHOR_KEY_ON_INFO, M2_BEHAVIOR_AUTHOR_KEY_ON_INIT,
    M2_BEHAVIOR_AUTHOR_KEY_ON_STATE_CHANGE, M2_BEHAVIOR_AUTHOR_KEY_ON_TERMINATE,
    M2_BEHAVIOR_KEY_ON_CALL, M2_BEHAVIOR_KEY_ON_CAST, M2_BEHAVIOR_KEY_ON_INFO,
    M2_BEHAVIOR_KEY_ON_INIT, M2_BEHAVIOR_KEY_ON_STATE_CHANGE, M2_BEHAVIOR_KEY_ON_TERMINATE,
    M2_KEY_BEHAVIOR, M2_KEY_LIMITS, M2_KEY_UPGRADE_FROM, M2_LIMITS_KEY_CPU, M2_LIMITS_KEY_FUEL,
    M2_LIMITS_KEY_MEMORY, M2_LIMITS_KEY_WALL_CLOCK, M2_UPGRADE_FROM_KEY_FROM,
    M2_UPGRADE_FROM_KEY_INSTRUCTIONS, M2_UPGRADE_INSTRUCTION_FIELD_KEY_MODULE,
    M2_UPGRADE_INSTRUCTION_FIELD_KEY_SCRIPT, M2_UPGRADE_INSTRUCTION_KEY_KIND,
    M2_UPGRADE_INSTRUCTION_KIND_LOAD_MODULE, M2_UPGRADE_INSTRUCTION_KIND_PURGE,
    M2_UPGRADE_INSTRUCTION_KIND_RESTART, M2_UPGRADE_INSTRUCTION_KIND_SOFT_PURGE,
    M2_UPGRADE_INSTRUCTION_KIND_STATE_CHANGE, M3_AUTHOR_KEY_CONTRATOS, M3_AUTHOR_KEY_ENTRADA,
    M3_AUTHOR_KEY_MEMBROS, M3_AUTHOR_KEY_PLACEMENT, M3_AUTHOR_KEY_POLITICAS, M3_KEY_PLACEMENT,
    M3_PLACEMENT_ESTRATEGIA_REPLICATED, M3_PLACEMENT_ESTRATEGIA_SHARDED,
    M3_PLACEMENT_ESTRATEGIA_SINGLE_NODE, M3_PLACEMENT_KEY_AFFINITY, M3_PLACEMENT_KEY_CLUSTERS,
    M3_PLACEMENT_KEY_ESTRATEGIA, M3_PLACEMENT_KEY_SHARD_KEY, MEMBRO_KEY_CAIXA, MEMBRO_KEY_VERSAO,
    MappingExt, MissingCiSlot, NATS_SUBJECT_MAX_LEN, OCI_SCHEME_PREFIX, PLEME_LABEL_PREFIX,
    POLITICAS_KEY_CIRCUIT_BREAKER, POLITICAS_KEY_MTLS_REQUIRED, POLITICAS_KEY_RATE_LIMIT,
    POLITICAS_KEY_RETRIES, POLITICAS_KEY_TIMEOUT, PathShapeViolation, RenderError, RenderedFile,
    STANDALONE_LAREIRA_ENABLED_DEFAULT, SUPERVISOR_AUTHOR_KEY_CHILDREN,
    SUPERVISOR_AUTHOR_KEY_ESTRATEGIA, SUPERVISOR_AUTHOR_KEY_MAX_RESTARTS,
    SUPERVISOR_AUTHOR_KEY_RESTART_WINDOW, SUPERVISOR_CHILD_KEY_CAIXA, SUPERVISOR_CHILD_KEY_RESTART,
    SUPERVISOR_CHILD_KEY_VERSAO, SUPERVISOR_CHILD_RESTART_PERMANENT,
    SUPERVISOR_CHILD_RESTART_TEMPORARY, SUPERVISOR_CHILD_RESTART_TRANSIENT,
    SUPERVISOR_ESTRATEGIA_ONE_FOR_ALL, SUPERVISOR_ESTRATEGIA_ONE_FOR_ONE,
    SUPERVISOR_ESTRATEGIA_REST_FOR_ONE, SUPERVISOR_ESTRATEGIA_SIMPLE_ONE_FOR_ONE,
    SUPERVISOR_KEY_CHILDREN, SUPERVISOR_KEY_ESTRATEGIA, SUPERVISOR_KEY_MAX_RESTARTS,
    SUPERVISOR_KEY_RESTART_WINDOW, SequenceExt, ServicoCountMismatch, WASI_KV_SLOT_MAX_LEN,
    WIT_IDENT_MAX_LEN, assert_str_reexport_identity, ci_declared_edge_count, cilium_auth_mode,
    cilium_network_policy_name, contrato_edge_label, decompose_ci, find_ascii_whitespace_byte,
    find_by_api_version, find_by_kind, find_by_label, find_by_name, find_by_namespace,
    find_non_ascii_whitespace_char, flux_kustomization_source_subtree, gateway_api_http_route_name,
    insert_first_seen, is_cargo_feature_name, is_computeunit_yaml_extension,
    is_digit_only_magnitude, is_dns_1123_label, is_gateway_api_http_path, is_git_oid,
    is_git_ref_name, is_git_repo_url, is_lareira_chart_name_shape,
    is_leading_zero_padded_magnitude, is_lisp_extension, is_nats_subject,
    is_sandboxed_relative_path, is_wasi_keyvalue_slot, is_wit_world_ref, kube_api_version,
    kube_api_version_is, kube_kind, kube_kind_is, kube_metadata, kube_metadata_field,
    kube_metadata_label, kube_metadata_label_is, kube_metadata_labels, kube_metadata_map_field,
    kube_metadata_str_field, kube_name, kube_name_is, kube_namespace, kube_namespace_is,
    kube_resource_skeleton, kube_root_str_field, kube_spec, kube_spec_field, kube_spec_map_field,
    kube_spec_seq_field, kube_spec_str_field, label_selector, lareira_chart_name, oci_chart_ref,
    pleme_program_in_aplicacao_selector, pleme_program_selector, require_acao_view,
    require_aplicacao_view, require_ci, require_kind, require_positive_bounded_u32,
    require_positive_bounded_u64, require_positive_canonical_bounded_duration,
    require_single_servico, require_v0_servico_shape, require_valid_dns_1123_label,
    require_valid_versao_requirement, servico_m2_overlay, servico_spec_and_m2_overlay_entries,
    single_field_overlay, singleton_mapping_sequence, string_keyed_entries, upsert_named_entry,
    yaml_string_mapping,
};
pub use supervisor::{
    ChildSpec, RestartPolicy, RestartStrategy, SUPERVISOR_MAX_RESTARTS_MAX,
    SUPERVISOR_RESTART_WINDOW_MAX, SupervisorError, SupervisorSpec,
};
pub use upgrade::{
    UpgradeError, UpgradeFromEntry, UpgradeInstruction, validate_upgrade_from,
    validate_upgrade_from_against_behavior, validate_upgrade_from_against_versao,
};
pub use version::{
    CaixaVersion, DEFAULT_GIT_REMOTE, DEFAULT_PLEME_GIT_ORG, DEFAULT_PUBLISH_TAG_PREFIX,
    VersionError, parse_requirement,
};
