use iac_forge::IacForgeError;
use iac_forge::backend::{ArtifactKind, Backend, GeneratedArtifact, NamingConvention};
use iac_forge::ir::{HasAttributes, IacDataSource, IacProvider, IacResource};

use crate::ferrite::{FerriteRuntime, ferrite_rt_import, ferrite_runtime_variant};
use crate::imports::stdlib_block;

pub struct FerriteTofuBackend {
    runtime: FerriteRuntime,
    naming: FerriteNaming,
}

impl FerriteTofuBackend {
    #[must_use]
    pub fn new(runtime: FerriteRuntime) -> Self {
        Self {
            runtime,
            naming: FerriteNaming,
        }
    }

    #[must_use]
    pub fn safe() -> Self {
        Self::new(FerriteRuntime::Safe)
    }

    #[must_use]
    pub fn arena() -> Self {
        Self::new(FerriteRuntime::Arena)
    }
}

pub struct FerriteNaming;

impl NamingConvention for FerriteNaming {
    fn resource_type_name(&self, resource_name: &str, provider_name: &str) -> String {
        format!("{provider_name}_{}", resource_name.replace('-', "_"))
    }

    fn file_name(&self, resource_name: &str, _kind: &ArtifactKind) -> String {
        format!("{}.go", resource_name.replace('-', "_"))
    }

    fn field_name(&self, api_name: &str) -> String {
        api_name.replace('-', "_")
    }
}

impl Backend for FerriteTofuBackend {
    fn platform(&self) -> &str {
        "opentofu-ferrite"
    }

    fn generate_resource(
        &self,
        resource: &IacResource,
        provider: &IacProvider,
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        let source = emit_go_resource(resource, provider, self.runtime);
        Ok(vec![GeneratedArtifact::new(
            self.naming
                .file_name(&resource.name, &ArtifactKind::Resource),
            source,
            ArtifactKind::Resource,
        )])
    }

    fn generate_data_source(
        &self,
        _ds: &IacDataSource,
        _provider: &IacProvider,
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        Ok(vec![])
    }

    fn generate_provider(
        &self,
        _provider: &IacProvider,
        _resources: &[IacResource],
        _data_sources: &[IacDataSource],
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        Ok(vec![])
    }

    fn generate_test(
        &self,
        _resource: &IacResource,
        _provider: &IacProvider,
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        Ok(vec![])
    }

    fn naming(&self) -> &dyn NamingConvention {
        &self.naming
    }
}

fn emit_go_resource(
    resource: &IacResource,
    provider: &IacProvider,
    runtime: FerriteRuntime,
) -> String {
    let pkg = provider.name.replace('-', "_");
    let tf_name = format!("{pkg}_{}", resource.name.replace('-', "_"));
    let struct_name = go_pascal(&resource.name);
    // Terraform resource type name (e.g. "aws_vpc") — burned into a header
    // comment so downstream tooling + humans can grep it.
    let _ = &tf_name;
    let variant = ferrite_runtime_variant(runtime);

    let imports = stdlib_block(&[ferrite_rt_import(runtime)]);

    let mut attrs_schema = String::new();
    let mut state_fields = String::new();
    for attr in resource.input_attributes() {
        let field = go_pascal(&attr.canonical_name);
        attrs_schema.push_str(&format!(
            "\t\t\t{:?}: schema.StringAttribute{{\n\t\t\t\tRequired: {},\n\t\t\t\tSensitive: {},\n\t\t\t}},\n",
            attr.canonical_name, attr.required, attr.sensitive
        ));
        state_fields.push_str(&format!(
            "\t{field} rt.Owned[string] `tfsdk:{:?}`\n",
            attr.canonical_name
        ));
    }

    format!(
        "// Code generated by caixa-provedor ({variant}). DO NOT EDIT.\n\
         //\n\
         // Provider:    {prov}\n\
         // Resource:    {res}\n\
         // TF type:     {tf_name}\n\
         // Runtime:     ferrite `{variant}` — every *T is Owned[T] by construction.\n\
         //\n\
         // Lifecycle:\n\
         //   - Create/Update/Delete borrow the request model mutably.\n\
         //   - Read borrows it immutably.\n\
         //   - All Owned[T] scopes end with an explicit Drop() — the generator\n\
         //     proves these by construction, so `ferrite-check` is a CI gate,\n\
         //     not the author.\n\
         \n\
         package {pkg}\n\
         \n\
         {imports}\n\
         type {struct_name}Resource struct{{}}\n\
         \n\
         type {struct_name}Model struct {{\n{state_fields}}}\n\
         \n\
         func (r *{struct_name}Resource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {{\n\
             resp.TypeName = req.ProviderTypeName + \"_{tf_name_suffix}\"\n\
         }}\n\
         \n\
         func (r *{struct_name}Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {{\n\
             resp.Schema = schema.Schema{{\n\
                 Attributes: map[string]schema.Attribute{{\n{attrs_schema}\t\t\t}},\n\
             }}\n\
         }}\n\
         \n\
         func (r *{struct_name}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {{\n\
             // Ferrite invariant: the request's Plan is borrowed mutably, written\n\
             // into a fresh Owned[{struct_name}Model], then Drop()ed when the function returns.\n\
             var plan {struct_name}Model\n\
             diags := req.Plan.Get(ctx, &plan)\n\
             resp.Diagnostics.Append(diags...)\n\
             if resp.Diagnostics.HasError() {{ return }}\n\
             // … CRUD call here …\n\
             diags = resp.State.Set(ctx, plan)\n\
             resp.Diagnostics.Append(diags...)\n\
         }}\n\
         \n\
         // Read/Update/Delete follow the same Owned-per-request pattern.\n\
         // Generated by caixa-provedor — scaffolding omitted for brevity.\n\
         \n\
         var _ resource.Resource = &{struct_name}Resource{{}}\n\
         \n\
         // Assert that every Owned[T] in this file has exactly one Drop on every\n\
         // control-flow path — the generator writes the code to satisfy this.\n\
         var _ = fmt.Sprintf(\"ferrite-check: ok\")\n",
        prov = provider.name,
        res = resource.name,
        tf_name_suffix = resource.name.replace('-', "_"),
    )
}

fn go_pascal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use iac_forge::ir::IacType;
    use iac_forge::testing::{TestAttributeBuilder, test_provider, test_resource};

    fn vpc() -> iac_forge::ir::IacResource {
        let mut r = test_resource("vpc");
        r.description = "VPC".into();
        r.attributes = vec![
            TestAttributeBuilder::new("cidr_block", IacType::String)
                .required()
                .description("CIDR")
                .build(),
        ];
        r
    }

    #[test]
    fn emits_ferrite_owned_fields() {
        let be = FerriteTofuBackend::safe();
        let artifacts = be.generate_resource(&vpc(), &test_provider("aws")).unwrap();
        let src = &artifacts[0].content;
        assert!(src.contains("rt.Owned[string]"));
        assert!(src.contains("ferrite/rt"));
        assert!(src.contains("aws_vpc"));
    }

    #[test]
    fn arena_runtime_swaps_import() {
        let be = FerriteTofuBackend::arena();
        let src = &be.generate_resource(&vpc(), &test_provider("aws")).unwrap()[0].content;
        assert!(src.contains("ferrite/rt/arena"));
        assert!(src.contains("ferrite-arena"));
    }
}
