//! Ferrite runtime flavor + import helpers.

/// Which ferrite runtime to target at emit time.
///
/// `Safe` → `ferrite/rt` (checked types, GC-compatible). The same binary
/// passes `ferrite-check` and can later be swapped to `Arena` via
/// `ferrite-mutate`.
///
/// `Arena` → `ferrite/rt/arena` (mmap regions, zero-GC). Final form.
///
/// The [`gen_platform::IsVariant`] derive emits per-arm
/// [`FerriteRuntime::is_safe`] / [`FerriteRuntime::is_arena`] predicates
/// every downstream ferrite-runtime-family gate keys off — the same
/// closed-set arm-discriminator discipline the sibling
/// `caixa_core::CaixaKind` / `caixa_core::CaixaDialeto` /
/// `caixa_core::PlacementStrategy` / `caixa_core::RestartStrategy` /
/// `caixa_core::RestartPolicy` / `caixa_core::DepList` /
/// `caixa_core::RateLimitUnit` / `caixa_core::render::PathShapeViolation`
/// / `caixa_arch::InvariantKind` / `caixa_arch::ArchVerdict` /
/// `caixa_lint::FixSafety` / `caixa_lint::Severity` closed-set fieldless
/// typed enums already carry. `Hash` joins the derive set so the enum
/// can live in arm-keyed sets (a future `feira publish-provider
/// --runtime-policy=<tier>` verb keying arm-specific counters, a future
/// admission-webhook rejection body naming the accepted runtime flavors).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, gen_platform::IsVariant)]
pub enum FerriteRuntime {
    Safe,
    Arena,
}

impl FerriteRuntime {
    /// Exhaustive iteration surface for every consumer that walks the
    /// closed two-arm [`FerriteRuntime`] discriminator set (the
    /// byte-parity witness against the paired [`gen_platform::IsVariant`]-
    /// derived [`Self::is_safe`] / [`Self::is_arena`] predicate family, a
    /// future `feira publish-provider --list-runtimes` CLI enumeration of
    /// the accepted runtime tags, a future admission-webhook rejection
    /// body naming the accepted runtime set, any future round-trip fuzz
    /// harness that sweeps every arm).
    ///
    /// A future variant addition (a `Region` tier between [`Self::Safe`]
    /// and [`Self::Arena`] for the intermediate `ferrite/rt/region`
    /// checked-arena flavor the ferrite roadmap grows) extends this
    /// slice as a single edit and every consumer picks up the new entry
    /// by construction; the compiler-checked exhaustiveness on the
    /// paired [`gen_platform::IsVariant`]-derived per-arm predicates
    /// covers the projection axis so both halves of the closed-set
    /// discipline migrate as one edit.
    ///
    /// Peer of the sibling closed-set fieldless typed enums'
    /// [`caixa_core::CaixaKind::ALL`] / [`caixa_core::CaixaDialeto::ALL`]
    /// / [`caixa_core::aplicacao::PlacementStrategy::ALL`] /
    /// [`caixa_core::supervisor::RestartStrategy::ALL`] /
    /// [`caixa_core::supervisor::RestartPolicy::ALL`] /
    /// [`caixa_core::dep::DepList::ALL`] /
    /// [`caixa_core::aplicacao::RateLimitUnit::ALL`] /
    /// [`caixa_core::render::PathShapeViolation::ALL`] /
    /// [`caixa_arch::invariants::InvariantKind::ALL`] /
    /// [`caixa_arch::report::ArchVerdict::ALL`] /
    /// [`caixa_lint::FixSafety::ALL`] / [`caixa_lint::Severity::ALL`]
    /// exhaustive-iteration surfaces — the thirteenth closed-set typed
    /// enum on the caixa surface (and the first inside `caixa-provedor`)
    /// to converge onto the same one-canonical-arm-list-per-enum
    /// discipline. Order matches variant declaration order verbatim
    /// (`Safe` → `Arena`).
    pub const ALL: &'static [Self] = &[Self::Safe, Self::Arena];

    /// Per-arm Go-import projection: the exact `rt "…"` line the
    /// ferrite-typed emit prepends inside its `import (…)` block. The
    /// canonical projection every ferrite-runtime-family consumer keys
    /// off — one typed dispatch on the substrate primitive replaces the
    /// pre-lift per-arm inline match at the two open-coded call sites
    /// [`crate::backend::emit_go_resource`] previously carried through
    /// the free-function [`ferrite_rt_import`] wrapper.
    #[must_use]
    pub const fn rt_import(self) -> &'static str {
        match self {
            Self::Safe => "rt \"github.com/pleme-io/ferrite/rt\"",
            Self::Arena => "rt \"github.com/pleme-io/ferrite/rt/arena\"",
        }
    }

    /// Short runtime-slug the emit-side burns into the generated
    /// file's header comment (`// Code generated by caixa-provedor
    /// (<variant-slug>). DO NOT EDIT.`). The canonical projection
    /// every ferrite-runtime-slug consumer keys off — one typed
    /// dispatch on the substrate primitive replaces the pre-lift
    /// per-arm inline match at [`crate::backend::emit_go_resource`]
    /// previously routed through the free-function
    /// [`ferrite_runtime_variant`] wrapper.
    #[must_use]
    pub const fn variant_slug(self) -> &'static str {
        match self {
            Self::Safe => "ferrite-safe",
            Self::Arena => "ferrite-arena",
        }
    }

    /// Reverse projection on the [`FerriteRuntime`] closed-set enum's
    /// canonical-slug axis — parses a `"ferrite-safe"` / `"ferrite-arena"`
    /// wire byte-string back to the typed enum, or returns `None` when
    /// `s` lies outside the two-arm accept-set [`Self::variant_slug`]
    /// emits. The single `&str → Self` projection every future re-entry
    /// point on the ferrite-runtime axis dispatches through (a future
    /// `feira publish-provider --runtime=<ferrite-safe|ferrite-arena>`
    /// CLI arg-parse that binds the wire byte-string into the typed
    /// enum before dispatching to the per-arm emitter, a future
    /// admission-webhook rejection body re-parsing a prior emission's
    /// header-comment slug back to the typed enum for policy-tier
    /// classification, a `tracing::field::Value::Str`-arm structured-
    /// log re-loader binding a prior `Display`-formatted output back
    /// to the typed enum for cross-run runtime-flavor histogram diff)
    /// would have had to re-inline a two-arm `match s` cascade that
    /// expressed no compile-time link back to the substrate primitive.
    ///
    /// Same closed-set-reverse-projection discipline the sibling
    /// [`caixa_core::CaixaKind::from_wire`] (2aa6d23) /
    /// [`caixa_core::CaixaDialeto::from_wire`] (d0e65ea) /
    /// [`caixa_core::supervisor::RestartStrategy::from_wire`] (4eec29c) /
    /// [`caixa_core::supervisor::RestartPolicy::from_wire`] (dd32ccf) /
    /// [`caixa_core::aplicacao::PlacementStrategy::from_wire`] (18c7342) /
    /// [`caixa_core::dep::DepList::from_wire`] (45ee563) /
    /// [`caixa_core::render::PathShapeViolation::from_wire`] (aebd9c6) /
    /// `caixa_arch::invariants::InvariantKind::from_wire` (b9e4e61) /
    /// `caixa_arch::report::ArchVerdict::from_wire` (6afe564) /
    /// `caixa_lint::diagnostic::Severity::from_wire` (5afff0e) /
    /// `caixa_lint::diagnostic::FixSafety::from_wire` (bd505a1) /
    /// `caixa_theme::style::Semantic::from_wire` (e7bca7b) typed enums
    /// carry on the peer wire-side `str → Self` axes — extends the
    /// substrate-wide `(as_str, from_wire)` round-trip family (here
    /// `(variant_slug, from_wire)`) onto the first `caixa-provedor`
    /// closed-set fieldless typed enum to converge on the reverse-
    /// projection discipline, matching the same two-way `str ↔ Self`
    /// round-trip every sibling closed-set enum already carries.
    /// Method-named `from_wire` (not `from_str`) to match the peer
    /// shapes verbatim and side-step a `clippy::should_implement_trait`
    /// lint that a plain `from_str` name would otherwise trigger
    /// without paired [`std::str::FromStr`] impl scaffolding this axis
    /// does not carry today. Returns `Option<Self>` (rather than
    /// `Result<Self, _>`) to match the peer shapes: the caller picks
    /// the diagnostic form appropriate for its use site (a future
    /// `feira publish-provider --runtime` CLI arg-parse renders its
    /// own per-verb error message; a future admission-webhook
    /// rejection body wraps the `None` outcome with the accepted-set
    /// enumeration `FerriteRuntime::ALL.iter().map(…)` for operator
    /// diagnostics).
    ///
    /// Pinned load-bearing at the substrate-primitive level by
    /// [`tests::ferrite_runtime_from_wire_accepts_every_variant_slug_output`]
    /// (round-trip witness against the peer [`Self::variant_slug`]
    /// axis) and
    /// [`tests::ferrite_runtime_from_wire_rejects_unknown_byte_strings`]
    /// (rejection witness against silent accept-set widening).
    #[must_use]
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "ferrite-safe" => Some(Self::Safe),
            "ferrite-arena" => Some(Self::Arena),
            _ => None,
        }
    }
}

/// Route the derived-style [`std::fmt::Display`] impl on
/// [`FerriteRuntime`] through the substrate-canonical
/// [`FerriteRuntime::variant_slug`] `pub const fn` accessor so every
/// consumer that binds a [`FerriteRuntime`] through the standard-
/// library `{}` formatting axis (a future `feira publish-provider`
/// per-runtime summary line, a `tracing::field::Value::Str`-arm
/// structured-log recorder on the emit path, any `format!("{runtime}")`
/// interpolation in a future emit-audit surface) reaches the same per-
/// arm kebab-case byte-string the pre-lift `variant_slug()` +
/// [`ferrite_runtime_variant`] free-function wrapper returns rather
/// than an open-coded per-arm match at every wire-up.
///
/// Follows the same closed-set-typed-enum `Display`-through-canonical-
/// projection convention the substrate-wide siblings
/// [`caixa_core::CaixaKind`] / [`caixa_core::CaixaDialeto`] /
/// [`caixa_core::aplicacao::PlacementStrategy`] /
/// [`caixa_core::aplicacao::RateLimitUnit`] /
/// [`caixa_core::supervisor::RestartStrategy`] /
/// [`caixa_core::supervisor::RestartPolicy`] /
/// [`caixa_core::dep::DepList`] / [`caixa_lint::Severity`] /
/// [`caixa_lint::FixSafety`] / [`caixa_arch::InvariantKind`] /
/// [`caixa_arch::ArchVerdict`] already carry through their paired
/// `as_str()` accessor, and the peer [`caixa_core::WitTarget`]
/// `Display`-through-`label()` route (aplicacao.rs:2427) carries on a
/// data-carrying typed enum whose canonical projection method is
/// domain-named rather than `as_str`. Extends the substrate-wide
/// closed-set-typed-enum `Display`-through-canonical-projection
/// discipline onto the caixa-provedor ferrite-runtime axis — the
/// first `caixa-provedor` closed-set typed enum to converge onto
/// the paired trait-impl half of the canonical projection triple.
///
/// The `variant_slug()` accessor is the canonical `&'static str` per-
/// arm projection on this enum (analog to `as_str()` on the sibling
/// caixa-core closed-set enums and `label()` on
/// [`caixa_core::WitTarget`]), returning `"ferrite-safe"` /
/// `"ferrite-arena"` — the same identity the file-header-comment
/// consumer at [`crate::backend::emit_go_resource`] burns into every
/// generated `// Code generated by caixa-provedor (<variant-slug>).
/// DO NOT EDIT.` prefix. Routing `Display` through it closes the
/// three-path convergence: `Debug` (the compiler-derived variant
/// name), `Display` (via `variant_slug`), and the emit-side header
/// slug all resolve to their canonical per-arm byte-string through
/// exactly one substrate-primitive dispatch per axis.
///
/// A future variant addition (a `Region` tier between [`Self::Safe`]
/// and [`Self::Arena`] for the intermediate `ferrite/rt/region`
/// checked-arena flavor the ferrite roadmap grows) reaches the
/// paired `Display` impl + [`AsRef<str>`] impl + every downstream
/// `.variant_slug()` consumer through one match-arm edit on
/// [`Self::variant_slug`] rather than a coordinated rewrite of every
/// open-coded per-arm match at every wire-up.
///
/// Pinned load-bearing by
/// [`tests::ferrite_runtime_display_and_as_ref_str_route_through_variant_slug_accessor`]
/// (three-path convergence pin: `Display`, `AsRef<str>`, and
/// `variant_slug` resolve to the same `&'static str` per arm) —
/// mirrors the peer `arch_verdict_display_and_as_ref_str_route_through_as_str_accessor`
/// (f3da79b) / `invariant_kind_display_and_as_ref_str_route_through_as_str_accessor`
/// (87c875a) / `fix_safety_display_and_as_ref_str_route_through_as_str_accessor`
/// (72782f7) pin shapes on the sibling caixa-arch / caixa-lint
/// closed-set-enum triple closures.
impl std::fmt::Display for FerriteRuntime {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.variant_slug())
    }
}

/// Route the standard-library [`AsRef<str>`] projection on
/// [`FerriteRuntime`] through the substrate-canonical
/// [`FerriteRuntime::variant_slug`] `pub const fn` accessor so every
/// consumer that binds a [`FerriteRuntime`] through the trait-
/// idiomatic `.as_ref()` (a future `HashMap::get::<str>(runtime.as_ref())`
/// per-runtime policy-table lookup, a `Command::arg` shell-out composing
/// the canonical runtime tag into a `feira publish-provider
/// --runtime=<tag>` filter, any `impl AsRef<str>`-bound generic
/// function) reaches the same per-arm kebab-case byte-string the
/// paired [`std::fmt::Display`] impl and the `variant_slug()` accessor
/// route through — one substrate-primitive dispatch per axis.
///
/// Peer of the substrate-wide sibling closed-set-enum
/// `AsRef<str>`-through-canonical-projection family — all ten
/// caixa-core / caixa-lint / caixa-arch closed-set fieldless typed
/// enums cited on the paired [`std::fmt::Display for FerriteRuntime`]
/// impl above. Rust-side newtype/typed-enum convention pairs
/// [`AsRef<str>`] and [`std::fmt::Display`] on the same primitive so
/// a caller who has one has both; before this lift,
/// [`FerriteRuntime`] carried neither trait impl even though its
/// canonical byte-string projection ([`Self::variant_slug`]) was
/// already established.
///
/// Pinned load-bearing on the same three-path convergence pin
/// [`tests::ferrite_runtime_display_and_as_ref_str_route_through_variant_slug_accessor`]
/// the sibling [`std::fmt::Display`] impl is pinned by — any future
/// silent detour that routes one impl through a divergent projection
/// (a per-arm inline `match self { … }` re-inlining that opens a
/// compile-time link to the un-lifted arm-literal, a swap onto the
/// sibling [`Self::rt_import`] Go-import projection that would
/// collide the runtime-slug axis with the import-line axis) trips at
/// caixa-provedor test time under `assert_eq!` rather than at a
/// downstream `impl AsRef<str>`-bound consumer's silent split.
impl AsRef<str> for FerriteRuntime {
    fn as_ref(&self) -> &str {
        self.variant_slug()
    }
}

/// Trait-idiomatic reverse projection on the [`FerriteRuntime`] closed
/// two-arm caixa-provedor ferrite-runtime axis — routes byte-for-byte
/// through the paired substrate-primitive [`FerriteRuntime::from_wire`]
/// `Option<Self>` accessor so every future consumer that binds a
/// canonical runtime slug through the standard-library `.try_into()` /
/// [`TryFrom`] axis (a future `feira publish-provider
/// --runtime=<slug>` CLI arg-parse composing into `let rt: FerriteRuntime
/// = s.try_into()?`, a future M4 provider-CR admission-webhook folding a
/// `spec.runtime: String` through `FerriteRuntime::try_from(&s)?`, a
/// generic `<T: TryFrom<&str>>`-bound provider-flavor loader over any of
/// the substrate's closed-set typed enums, a future `caixa provedor
/// switch --runtime <ferrite-safe|ferrite-arena>` verb) reaches the
/// same two-arm accept-set the sibling [`FerriteRuntime::from_wire`]
/// resolver parses through and the sibling [`FerriteRuntime::variant_slug`]
/// emits, rather than an open-coded per-arm
/// `match s { "ferrite-safe" => …, "ferrite-arena" => …, _ => … }`
/// cascade whose arm-set has no compile-time link back to the substrate
/// primitive.
///
/// Complements the pre-existing forward-projection triple
/// ([`std::fmt::Display`], [`AsRef<str>`], [`FerriteRuntime::variant_slug`])
/// with the paired trait-idiomatic reverse-projection axis: Rust-side
/// newtype/typed-enum convention pairs [`AsRef<str>`] with either
/// [`std::str::FromStr`] or [`TryFrom<&str>`] on the same primitive so a
/// caller who can project *out to* a `&str` can also project *in from*
/// one. The [`TryFrom<&str>`] axis is deliberately chosen over
/// [`std::str::FromStr`] to sidestep the `clippy::should_implement_trait`
/// lint the sibling method-named [`FerriteRuntime::from_wire`] would
/// trigger under a `FromStr` impl (the same design tradeoff the peer
/// [`caixa_core::CaixaKind`] (3c83606), [`caixa_core::CaixaDialeto`]
/// (bf33136), [`caixa_core::aplicacao::PlacementStrategy`] (6fd00cd),
/// [`caixa_core::supervisor::RestartStrategy`] (5b828ed),
/// [`caixa_core::supervisor::RestartPolicy`] (6fdd0d9),
/// [`caixa_core::aplicacao::WitShape`] (5472902),
/// [`caixa_core::aplicacao::RateLimitUnit`] (bf78400),
/// [`caixa_core::render::PathShapeViolation`] (e67e48a),
/// `caixa_arch::invariants::InvariantKind` (e21a857),
/// `caixa_arch::report::ArchVerdict` (0a4cc45),
/// `caixa_lint::diagnostic::Severity` (a7bf74c),
/// `caixa_lint::diagnostic::FixSafety` (df86c94), and
/// `caixa_theme::style::Semantic` (bd7da69) blocks note) — this impl
/// closes the trait-idiomatic reverse axis without disturbing the
/// method-named `from_wire` shape every peer closed-set typed enum
/// already carries.
///
/// `type Error = ()` matches the sibling [`FerriteRuntime::from_wire`]'s
/// `Option<Self>` return-shape's deliberate deferral of error typing:
/// the caller picks the diagnostic form appropriate for its use site
/// (a future `feira publish-provider --runtime` CLI arg-parse composes
/// its own per-verb "unknown ferrite-runtime slug: <arg> — accepted:
/// {…}" message enumerating [`FerriteRuntime::ALL`], a future M4
/// provider-CR admission-webhook wraps `Err(())` with a per-CR
/// structured refusal body enumerating the two-arm accept-set, a
/// `Result::map_err` at the call site lifts the axis-error to a per-
/// verb error type). Same shape every peer sibling reverse-projection
/// axis carries.
///
/// The paired [`TryFrom<&str>`] impl reaches the same two-arm accept-
/// set the [`FerriteRuntime::from_wire`] resolver dispatches through,
/// so any future variant addition (a `Region` tier between [`Self::Safe`]
/// and [`Self::Arena`] for the intermediate `ferrite/rt/region`
/// checked-arena flavor the ferrite roadmap grows — the trajectory item
/// every sibling [`FerriteRuntime`] doc block already names) grows the
/// trait-idiomatic axis by construction: one caixa-provedor edit on
/// [`FerriteRuntime::from_wire`] extends both the method-named reverse
/// projection every existing consumer keys off and the trait-idiomatic
/// reverse projection this impl exposes, without a coordinated rewrite
/// across every future `TryFrom<&str>`-bound consumer's arm-set.
///
/// Extends the substrate-wide closed-set-enum trait-idiomatic reverse-
/// projection family ([`caixa_core::CaixaKind`] via 3c83606,
/// [`caixa_core::CaixaDialeto`] via bf33136,
/// [`caixa_core::aplicacao::PlacementStrategy`] via 6fd00cd,
/// [`caixa_core::supervisor::RestartStrategy`] via 5b828ed,
/// [`caixa_core::supervisor::RestartPolicy`] via 6fdd0d9,
/// [`caixa_core::aplicacao::WitShape`] via 5472902,
/// [`caixa_core::aplicacao::RateLimitUnit`] via bf78400,
/// [`caixa_core::render::PathShapeViolation`] via e67e48a,
/// `caixa_arch::invariants::InvariantKind` via e21a857,
/// `caixa_arch::report::ArchVerdict` via 0a4cc45,
/// `caixa_lint::diagnostic::Severity` via a7bf74c,
/// `caixa_lint::diagnostic::FixSafety` via df86c94, and
/// `caixa_theme::style::Semantic` via bd7da69) onto the first closed-
/// set fieldless typed enum on the caixa-provedor surface — the
/// ferrite-runtime two-arm accept-set every emit-side header comment
/// (`// Code generated by caixa-provedor (<variant-slug>). DO NOT EDIT.`),
/// every ferrite-runtime-family gate, and every future
/// provider-CR admission-webhook keys off. The fourteenth and final
/// peer on the substrate surface — this lift closes the trait-idiomatic
/// reverse-projection campaign across every closed-set fieldless typed
/// enum in the caixa workspace.
///
/// Pinned load-bearing by
/// [`tests::ferrite_runtime_try_from_str_routes_through_from_wire_accessor`]
/// (byte-parity pin against [`FerriteRuntime::from_wire`] across the
/// two-arm accept-set),
/// [`tests::ferrite_runtime_try_from_str_rejects_unknown_byte_strings`]
/// (rejection witness against silent accept-set widening), and
/// [`tests::ferrite_runtime_try_from_str_and_from_wire_partition_the_accept_set`]
/// (cross-axis partition pin locking trait and method-named projections
/// to the same `Option<Self>` output on every input).
impl TryFrom<&str> for FerriteRuntime {
    type Error = ();

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::from_wire(s).ok_or(())
    }
}

/// Standard-library trait-idiomatic forward projection on the
/// [`FerriteRuntime`] closed two-arm caixa-provedor ferrite-runtime
/// axis. Routes byte-for-byte through the paired substrate-primitive
/// [`FerriteRuntime::variant_slug`] `pub const fn` accessor so
/// `<&'static str>::from(rt)` / `rt.into::<&'static str>()` reaches the
/// same two-arm canonical-lowercase kebab emit-set the sibling method-
/// named accessor dispatches through and the sibling
/// [`std::fmt::Display for FerriteRuntime`] / [`AsRef<str> for FerriteRuntime`]
/// impls also route through.
///
/// Extends the substrate-wide closed-set-enum trait-idiomatic
/// forward-projection family
/// ([`caixa_core::supervisor::RestartStrategy`] via 523157d,
/// [`caixa_core::supervisor::RestartPolicy`] via 9fb37d0,
/// [`caixa_core::CaixaKind`] via edb827b,
/// [`caixa_core::CaixaDialeto`] via c189a6f,
/// [`caixa_core::aplicacao::PlacementStrategy`] via afa3562,
/// [`caixa_core::aplicacao::WitShape`] via 56998ec,
/// [`caixa_core::aplicacao::RateLimitUnit`] via 7fdfbf4,
/// [`caixa_core::render::PathShapeViolation`] via 070a6de,
/// [`caixa_arch::invariants::InvariantKind`] via f2ca7bc,
/// [`caixa_arch::report::ArchVerdict`] via d4559cb,
/// `caixa_lint::diagnostic::Severity` via 5cc3b8b,
/// `caixa_lint::diagnostic::FixSafety` via 2a56127, and
/// `caixa_theme::style::Semantic` via 07f36bb) onto the last
/// closed-set fieldless typed enum on the caixa-provedor surface — the
/// ferrite-runtime two-arm accept-set every emit-side header comment
/// (`// Code generated by caixa-provedor (<variant-slug>). DO NOT EDIT.`),
/// every ferrite-runtime-family gate, every future
/// provider-CR admission-webhook per-runtime policy-tier reply, every
/// `HashMap::<&'static str, _>::from_iter(FerriteRuntime::ALL.iter()
/// .map(|&rt| (rt.into(), …)))`-style per-runtime table lookup, and
/// every future `<T: Into<&'static str>>`-bound provider-flavor
/// registrar keys off. The fourteenth and final peer on the substrate
/// surface — this lift closes the trait-idiomatic forward-projection
/// campaign across every closed-set fieldless typed enum in the caixa
/// workspace.
///
/// Pairs with the sibling [`TryFrom<&str> for FerriteRuntime`] impl
/// (42ab951) to close the two-way `Self ↔ &'static str` round-trip on
/// the trait-idiomatic axis pair, mirroring the pre-existing method-
/// named [`FerriteRuntime::variant_slug`] + [`FerriteRuntime::from_wire`]
/// pair on the substrate-primitive axis pair.
///
/// Return type is `&'static str` by construction — every
/// [`FerriteRuntime::variant_slug`] arm resolves to an inline
/// `"ferrite-safe"` / `"ferrite-arena"` `&'static str` literal, so the
/// trait's return-type promise is upheld structurally without a
/// [`String::leak`] cast or a per-arm inline literal outside the paired
/// [`FerriteRuntime::variant_slug`] dispatch.
///
/// The paired [`FerriteRuntime::variant_slug`] accessor's two-arm
/// emit-set is the single source of truth — every future arm addition
/// (a `Region` tier between [`Self::Safe`] and [`Self::Arena`] for the
/// intermediate `ferrite/rt/region` checked-arena flavor the ferrite
/// roadmap grows — the trajectory item every sibling
/// [`FerriteRuntime`] doc block already names) grows the trait-
/// idiomatic forward axis by construction: one caixa-provedor edit on
/// [`FerriteRuntime::variant_slug`] extends every one of the sibling
/// forward-projection paths ([`std::fmt::Display`], [`AsRef<str>`],
/// [`FerriteRuntime::variant_slug`] itself, and this
/// [`From<Self> for &'static str`]) without a coordinated rewrite
/// across every future `Into<&'static str>`-bound consumer's arm-set.
///
/// Pinned load-bearing by
/// [`tests::ferrite_runtime_from_into_static_str_routes_through_variant_slug_accessor`]
/// (byte-parity pin against [`FerriteRuntime::variant_slug`] across the
/// two-arm emit-set, plus a `const`-context materialization witness for
/// the `&'static str` lifetime promise routed through the paired
/// [`FerriteRuntime::variant_slug`] `pub const fn` accessor, plus a
/// paired `.into()` shape assertion covering the blanket-derived
/// `Into<&'static str>` shape) and
/// [`tests::ferrite_runtime_from_into_static_str_and_variant_slug_partition_the_emit_set`]
/// (partition pin asserting `<&'static str as From<FerriteRuntime>>::from`
/// and [`FerriteRuntime::variant_slug`] agree on every arm, plus a
/// two-way direct round-trip witness through the paired trait-idiomatic
/// [`TryFrom<&str>`] axis that closes the two-way
/// `Self ↔ &'static str` round-trip on the trait-idiomatic axis pair
/// — the emit-side [`FerriteRuntime::variant_slug`] and the parse-side
/// [`FerriteRuntime::from_wire`] dispatch on the same two inline
/// canonical-lowercase kebab byte-strings by construction, so round-
/// tripping composes the two trait impls directly).
impl From<FerriteRuntime> for &'static str {
    fn from(runtime: FerriteRuntime) -> &'static str {
        runtime.variant_slug()
    }
}

/// Trait-idiomatic *borrowed-input* forward projection on
/// [`FerriteRuntime`] onto the `&'static str` axis — the borrowed-input
/// companion to the paired owned-input [`From<FerriteRuntime> for
/// &'static str`] impl immediately above. Routes byte-for-byte through
/// the same substrate-primitive [`FerriteRuntime::variant_slug`] `pub
/// const fn` accessor so every consumer that binds a `&FerriteRuntime`
/// through the standard-library `.into()` / [`From<&Self> for &'static
/// str`] axis (a `FerriteRuntime::ALL.iter().map(<&'static
/// str>::from).collect::<Vec<_>>()` per-arm accept-set materializer —
/// whose iterator over `&'static [FerriteRuntime]` yields
/// `&FerriteRuntime`, not `FerriteRuntime`, so the owned-input
/// [`From<FerriteRuntime>`] axis alone forces every call site through
/// an explicit `.copied()` / dereference / [`Copy`]-bound restatement
/// rather than the direct trait-idiomatic projection; a future
/// `feira publish-provider --list-runtimes` CLI enumeration composed
/// via `FerriteRuntime::ALL.iter().map(Into::into)`; a future M4
/// admission-webhook rejection body whose accepted-runtime-set
/// enumeration walks the same iterator shape; a future
/// `HashMap::<&'static str, usize>::from_iter(runtimes.iter().map(
///     |rt| (<&'static str>::from(rt), 0)))` per-runtime-tier
/// histogram seed on a future `feira publish-provider` audit-report
/// path — whose borrowed access off `&Provider.runtime` avoids a
/// `.copied()` / [`Copy`]-bound dereference on the ferrite-runtime
/// field) reaches the same two-arm `"ferrite-safe"` / `"ferrite-arena"`
/// canonical-lowercase kebab emit-set the paired owned-input
/// [`From<FerriteRuntime> for &'static str`], the sibling
/// [`std::fmt::Display`], [`AsRef<str>`], and
/// [`FerriteRuntime::variant_slug`] surfaces already return.
///
/// Fourteenth and final peer on the substrate-wide trait-idiomatic
/// *borrowed-input* `&'static str`-returning forward-projection family
/// already carried by [`caixa_core::dep::DepList`] (64aa742,
/// first-mover), [`caixa_core::CaixaKind`],
/// [`caixa_core::CaixaDialeto`],
/// [`caixa_core::supervisor::RestartStrategy`],
/// [`caixa_core::supervisor::RestartPolicy`],
/// [`caixa_core::aplicacao::PlacementStrategy`],
/// [`caixa_core::aplicacao::WitShape`],
/// [`caixa_core::aplicacao::RateLimitUnit`],
/// [`caixa_core::render::PathShapeViolation`] (cdf4e95, first render-
/// side arm), [`caixa_arch::invariants::InvariantKind`] (238d886,
/// first outside-`caixa-core` arm), [`caixa_arch::report::ArchVerdict`]
/// (73bda50), [`caixa_lint::diagnostic::Severity`] (2b9003f),
/// [`caixa_lint::diagnostic::FixSafety`] (d8769ab), and the paired
/// sibling [`caixa_theme::style::Semantic`] axis. Rust's `From` trait
/// does not auto-derive the `From<&Self>` sibling from a `From<Self>`
/// impl (the blanket `impl<T, U> From<&T> for U where T: Copy, U:
/// From<T>` does not exist in `core`), so every closed-set typed enum
/// that carries the owned-input axis but not the borrowed-input axis
/// forces every borrowed-input call site through a `.copied()` /
/// `<&'static str>::from(*runtime)` / `runtime.variant_slug()` detour
/// whose type bounds have no compile-time link to the substrate
/// primitive. Lifting the borrowed-input axis on the caixa-provedor
/// ferrite-runtime two-arm closed-set fieldless typed enum closes that
/// gap on the same trajectory the paired owned-input axis
/// ([`impl From<FerriteRuntime> for &'static str`] immediately above)
/// already opened, and closes the trait-idiomatic *borrowed-input*
/// `&'static str`-returning axis on the caixa-provedor crate (the sole
/// closed-set fieldless typed enum on the caixa-provedor surface).
///
/// Opens the 2×2-completion corner on this outside-`caixa-core`
/// closed-set typed enum — the caixa-theme [`Semantic`] axis remains
/// the last future target of this 2×2-completion campaign after this
/// lift lands.
///
/// Pinned load-bearing by
/// [`tests::ferrite_runtime_from_borrowed_into_static_str_routes_through_variant_slug_accessor`]
/// (byte-parity pin against [`FerriteRuntime::variant_slug`] across the
/// two-arm emit-set via a borrowed input, plus a `const`-context
/// materialization witness for the `&'static str` lifetime promise)
/// and
/// [`tests::ferrite_runtime_from_owned_and_borrowed_into_static_str_agree_on_every_arm`]
/// (cross-axis partition pin against the paired owned-input
/// [`From<FerriteRuntime> for &'static str`] impl, plus a
/// `.iter().map(Into::into)` pipe witness over
/// [`FerriteRuntime::ALL`] whose iterator yields `&FerriteRuntime` by
/// construction so this borrowed-input axis is what routes the pipe
/// through the substrate-primitive accessor without a spurious `Copy`
/// deref).
impl From<&FerriteRuntime> for &'static str {
    fn from(runtime: &FerriteRuntime) -> &'static str {
        runtime.variant_slug()
    }
}

/// Trait-idiomatic *owned-input, owned-`String` output* forward
/// projection on [`FerriteRuntime`] onto the owned-`String` axis —
/// the owned-`String` companion to the paired
/// [`From<FerriteRuntime> for &'static str`] and
/// [`From<&FerriteRuntime> for &'static str`] siblings immediately
/// above. Routes byte-for-byte through the substrate-primitive
/// [`FerriteRuntime::variant_slug`] `pub const fn` accessor via
/// [`str::to_owned`] so every consumer that binds a
/// [`FerriteRuntime`] through the standard-library `.into()` /
/// [`From<Self> for String`] axis (a `let key: String =
/// runtime.into();`-shaped downstream call site; a future
/// `serde_json::Value::String(runtime.into())` structured-payload
/// composer on a future `feira publish-provider` audit-report path
/// where the `Value::String` arm typing demands an owned [`String`]
/// and the sibling `&'static str`-returning axes force an explicit
/// `.to_owned()` / [`String::from`] restatement at every call site;
/// a future `HashMap::<String, FerriteRuntime>::from_iter` per-
/// runtime lookup on the operator's provider-registry path where the
/// map's key type is owned [`String`] rather than `&'static str`; a
/// future [`std::borrow::Cow::<'static, str>::Owned(runtime.into())`]
/// composer on a future M4 admission-webhook rejection body's owned-
/// arm; a future caixa-provedor pipeline's per-provider structured-
/// log emit where the JSON serializer's [`Serialize`] impl on
/// [`String`] owns the emit-path) reaches the same two-arm
/// `"ferrite-safe"` / `"ferrite-arena"` canonical-lowercase kebab
/// emit-set the paired `&'static str`-returning axes, the sibling
/// [`std::fmt::Display`], [`AsRef<str>`], and
/// [`FerriteRuntime::variant_slug`] surfaces already return — no
/// `.to_owned()` / `String::from(runtime.variant_slug())` detour
/// whose type bounds have no compile-time link to the substrate
/// primitive.
///
/// Rust's standard library does not carry a blanket
/// `impl<T: AsRef<str>> From<T> for String` (nor an
/// `impl<T: fmt::Display> From<T> for String`), so every closed-set
/// typed enum that carries the paired [`AsRef<str>`] /
/// [`std::fmt::Display`] / [`From<Self> for &'static str`] /
/// [`From<&Self> for &'static str`] quadruple but not the owned-
/// `String` axis forces every owned-string call site through the
/// detour above. This lift closes that axis on the sole closed-set
/// fieldless typed enum on the caixa-provedor surface (the
/// ferrite-runtime two-arm axis), matching the trajectory each of
/// the eleven prior peer enums —
/// [`caixa_core::supervisor::RestartStrategy`] (7baa18a, first-mover
/// on this axis), [`caixa_core::supervisor::RestartPolicy`] (7851725),
/// [`caixa_core::CaixaKind`] (231a18c),
/// [`caixa_core::CaixaDialeto`] (88942cd),
/// [`caixa_core::dep::DepList`] (32b0ee8),
/// [`caixa_core::aplicacao::PlacementStrategy`] (1154c2f),
/// [`caixa_core::aplicacao::WitShape`] (79a8723),
/// [`caixa_core::aplicacao::RateLimitUnit`] (c7d687d),
/// [`caixa_core::render::PathShapeViolation`] (6e0479a, first render-
/// side arm), [`caixa_arch::invariants::InvariantKind`] (1afd8d5,
/// first outside-`caixa-core` arm — the paired severity-classification
/// axis on the caixa-arch invariant-kind closed-set enum), and
/// [`caixa_arch::report::ArchVerdict`] (cc80a53, the paired verdict-
/// outcome axis on the sibling caixa-arch closed-set enum) —
/// followed on the same 2×2-completion campaign.
///
/// Pinned load-bearing by
/// [`tests::ferrite_runtime_from_into_owned_string_routes_through_variant_slug_accessor`]
/// (byte-parity pin against [`FerriteRuntime::variant_slug`] across
/// the two-arm emit-set via the owned-`String` surface) and
/// [`tests::ferrite_runtime_from_into_owned_string_and_static_str_agree_on_every_arm`]
/// (cross-axis partition pin against the paired owned-input
/// `&'static str`-returning [`From<FerriteRuntime> for &'static str`]
/// impl and the [`ToString::to_string`]-through-[`std::fmt::Display`]
/// surface, plus a `.iter().copied().map(String::from)` pipe witness
/// over [`FerriteRuntime::ALL`], plus a direct `Self → String → Self`
/// round-trip witness through the paired [`TryFrom<&str>`] axis on
/// the owned-[`String`]'s [`String::as_str`] borrow).
impl From<FerriteRuntime> for String {
    fn from(runtime: FerriteRuntime) -> String {
        runtime.variant_slug().to_owned()
    }
}

/// Free-function wrapper preserved for the crate-level `pub use`
/// re-export in [`crate`]; routes through the substrate-primitive
/// method [`FerriteRuntime::rt_import`].
#[must_use]
pub fn ferrite_rt_import(runtime: FerriteRuntime) -> &'static str {
    runtime.rt_import()
}

/// Free-function wrapper preserved for the crate-level `pub use`
/// re-export in [`crate`]; routes through the substrate-primitive
/// method [`FerriteRuntime::variant_slug`].
#[must_use]
pub const fn ferrite_runtime_variant(runtime: FerriteRuntime) -> &'static str {
    runtime.variant_slug()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ferrite_runtime_all_lists_every_variant_in_declaration_order() {
        // Fail-before-pass-after pin on the [`gen_platform::IsVariant`]
        // derive's per-arm-list-per-enum discipline for
        // [`FerriteRuntime`]: any future variant addition (a `Region`
        // tier between [`FerriteRuntime::Safe`] and
        // [`FerriteRuntime::Arena`] for the intermediate
        // `ferrite/rt/region` checked-arena flavor the ferrite roadmap
        // grows) that lands the new variant on the enum without
        // extending [`FerriteRuntime::ALL`] trips this test — the
        // compiler-checked exhaustiveness on the paired
        // [`gen_platform::IsVariant`]-derived per-arm predicates
        // ([`FerriteRuntime::is_safe`] / [`FerriteRuntime::is_arena`])
        // covers the projection axis; this pin covers the
        // exhaustive-iteration axis so both halves of the closed-set
        // discipline migrate as one edit.
        assert_eq!(
            FerriteRuntime::ALL,
            &[FerriteRuntime::Safe, FerriteRuntime::Arena],
        );
        // Every arm satisfies exactly one of the paired per-arm
        // predicates — the byte-parity pin between the
        // [`FerriteRuntime::ALL`] iteration axis and the per-arm
        // [`gen_platform::IsVariant`]-derived predicate axis.
        for arm in FerriteRuntime::ALL {
            assert_eq!(
                usize::from(arm.is_safe()) + usize::from(arm.is_arena()),
                1,
                "FerriteRuntime::{arm:?} must satisfy exactly one of \
                 is_safe / is_arena",
            );
        }
    }

    #[test]
    fn ferrite_runtime_predicates_are_byte_equal_to_matches_family() {
        // Fail-before-pass-after pin on the two-arm convergence of the
        // pre-lift per-arm inline `match (runtime) { Safe => …, Arena
        // => … }` sites the two free-function projections
        // ([`ferrite_rt_import`], [`ferrite_runtime_variant`]) carried
        // onto the [`gen_platform::IsVariant`]-derive-generated per-arm
        // predicate family: for every arm, each predicate agrees
        // byte-for-byte with the pre-lift `matches!(_,
        // FerriteRuntime::…)` shape.
        //
        // A future rebrand touching either endpoint (a
        // `#[is_variant(name = "…")]` attribute drift on the derive, an
        // arm rename, an accidental peer predicate that shadows the
        // derive-generated one) would silently split the two paths and
        // trip this pin.
        for arm in FerriteRuntime::ALL {
            assert_eq!(
                arm.is_safe(),
                matches!(arm, FerriteRuntime::Safe),
                "FerriteRuntime::{arm:?}.is_safe() must agree with \
                 matches!(_, FerriteRuntime::Safe) byte-for-byte",
            );
            assert_eq!(
                arm.is_arena(),
                matches!(arm, FerriteRuntime::Arena),
                "FerriteRuntime::{arm:?}.is_arena() must agree with \
                 matches!(_, FerriteRuntime::Arena) byte-for-byte",
            );
        }
    }

    #[test]
    fn ferrite_runtime_projections_are_stable_per_arm_across_all() {
        // Accessor-level byte-parity pin: for every arm in
        // [`FerriteRuntime::ALL`], both projections
        // ([`FerriteRuntime::rt_import`] / [`FerriteRuntime::variant_slug`])
        // return the exact byte-string the pre-lift free-function form
        // ([`ferrite_rt_import`] / [`ferrite_runtime_variant`]) emitted.
        // This pin guards against a future silent split between the
        // free-function wrappers, the inherent-method projections, and
        // the two open-coded emit-side call sites in
        // [`crate::backend::emit_go_resource`] — any drift on the
        // canonical per-arm byte-string surfaces as a test failure
        // here rather than at downstream `go build` or `ferrite-check`
        // time.
        for arm in FerriteRuntime::ALL {
            assert_eq!(arm.rt_import(), ferrite_rt_import(*arm));
            assert_eq!(arm.variant_slug(), ferrite_runtime_variant(*arm));
        }
        // Pin the exact byte-shapes so a future rebrand of either the
        // `rt "…"` line or the header-comment slug surfaces here.
        assert_eq!(
            FerriteRuntime::Safe.rt_import(),
            "rt \"github.com/pleme-io/ferrite/rt\"",
        );
        assert_eq!(
            FerriteRuntime::Arena.rt_import(),
            "rt \"github.com/pleme-io/ferrite/rt/arena\"",
        );
        assert_eq!(FerriteRuntime::Safe.variant_slug(), "ferrite-safe");
        assert_eq!(FerriteRuntime::Arena.variant_slug(), "ferrite-arena");
    }

    #[test]
    fn ferrite_runtime_display_and_as_ref_str_route_through_variant_slug_accessor() {
        // Fail-before-pass-after three-path convergence pin: for every
        // arm in [`FerriteRuntime::ALL`], the paired
        // [`std::fmt::Display`] impl and [`AsRef<str>`] impl and the
        // substrate-canonical [`FerriteRuntime::variant_slug`] accessor
        // resolve to the same `&'static str` per arm. Mirrors the peer
        // `arch_verdict_display_and_as_ref_str_route_through_as_str_accessor`
        // (f3da79b) /
        // `invariant_kind_display_and_as_ref_str_route_through_as_str_accessor`
        // (87c875a) /
        // `fix_safety_display_and_as_ref_str_route_through_as_str_accessor`
        // (72782f7) pin shapes on the sibling caixa-arch / caixa-lint
        // closed-set-enum triple closures, extended onto the caixa-
        // provedor ferrite-runtime axis.
        //
        // Any future silent detour that routes one impl through a
        // divergent projection (a per-arm inline `match self { … }` re-
        // inlining that opens a compile-time link to the un-lifted arm-
        // literal, a swap onto the sibling [`FerriteRuntime::rt_import`]
        // Go-import projection that would collide the runtime-slug axis
        // with the import-line axis, an arm rename touching one impl but
        // not the paired sibling) trips at caixa-provedor test time
        // under `assert_eq!` rather than at a downstream `impl
        // AsRef<str>`-bound consumer's silent split or a `format!
        // ("{runtime}")` audit-line divergence.
        for arm in FerriteRuntime::ALL {
            let via_slug = arm.variant_slug();
            let via_display = format!("{arm}");
            let via_as_ref = <FerriteRuntime as AsRef<str>>::as_ref(arm);
            assert_eq!(
                via_display, via_slug,
                "FerriteRuntime::{arm:?} Display must byte-equal \
                 variant_slug() — got {via_display:?} vs {via_slug:?}",
            );
            assert_eq!(
                via_as_ref, via_slug,
                "FerriteRuntime::{arm:?} AsRef<str> must byte-equal \
                 variant_slug() — got {via_as_ref:?} vs {via_slug:?}",
            );
        }
        // Pin the exact per-arm byte-string on both trait impls so a
        // future rebrand of the canonical slug ("ferrite-safe" /
        // "ferrite-arena") surfaces at this pin rather than at a
        // downstream consumer's silent tag drift.
        assert_eq!(format!("{}", FerriteRuntime::Safe), "ferrite-safe");
        assert_eq!(format!("{}", FerriteRuntime::Arena), "ferrite-arena");
        assert_eq!(
            <FerriteRuntime as AsRef<str>>::as_ref(&FerriteRuntime::Safe),
            "ferrite-safe",
        );
        assert_eq!(
            <FerriteRuntime as AsRef<str>>::as_ref(&FerriteRuntime::Arena),
            "ferrite-arena",
        );
    }

    #[test]
    fn ferrite_runtime_from_wire_accepts_every_variant_slug_output() {
        // Fail-before-pass-after per-arm accept pin on the newly lifted
        // [`FerriteRuntime::from_wire`] reverse projection: every arm
        // in [`FerriteRuntime::ALL`] must parse back through `from_wire`
        // when fed its own [`FerriteRuntime::variant_slug`] output,
        // landing on `Some(same_variant)`. A regression that hand-rolled
        // either side's per-arm match without threading through the
        // shared two-string closed set would silently disagree on any
        // future arm rename (or a new arm the ferrite roadmap grows — a
        // `Region` tier between [`FerriteRuntime::Safe`] and
        // [`FerriteRuntime::Arena`] for the intermediate
        // `ferrite/rt/region` checked-arena flavor) and this pin flags
        // it at caixa-provedor build time rather than at a downstream
        // `feira publish-provider --runtime` consumer's silent tag
        // misclassification.
        //
        // Peer of the sibling
        // `caixa_theme::style::tests::semantic_from_wire_accepts_every_as_str_output`
        // (e7bca7b) /
        // `caixa_lint::diagnostic::tests::fix_safety_from_wire_accepts_every_as_str_output`
        // (bd505a1) /
        // `caixa_lint::diagnostic::tests::severity_from_wire_accepts_every_as_str_output`
        // (5afff0e) /
        // `caixa_arch::report::tests::arch_verdict_from_wire_accepts_every_as_str_output`
        // (6afe564) /
        // `caixa_arch::invariants::tests::invariant_kind_from_wire_accepts_every_as_str_output`
        // (b9e4e61) round-trip pins on the peer caixa-theme / caixa-lint
        // / caixa-arch closed-set-enum reverse-projection axes, and of
        // the sibling
        // `caixa_core::kind::tests::caixa_kind_wire_round_trips_through_from_wire`
        // (2aa6d23) /
        // `caixa_core::dialeto::tests::caixa_dialeto_from_wire_accepts_every_as_str_output`
        // (d0e65ea) /
        // `caixa_core::aplicacao::tests::placement_strategy_from_wire_accepts_every_lifted_constant`
        // (18c7342) /
        // `caixa_core::dep::tests::dep_list_round_trips_through_as_str_and_from_wire`
        // (45ee563) /
        // `caixa_core::render::tests::path_shape_violation_from_wire_accepts_every_as_str_output`
        // (aebd9c6) round-trip pins on the sibling caixa-core closed-
        // set typed-enum reverse-projection axes.
        for &variant in FerriteRuntime::ALL {
            let wire = variant.variant_slug();
            let parsed = FerriteRuntime::from_wire(wire).unwrap_or_else(|| {
                panic!(
                    "FerriteRuntime::from_wire({wire:?}) must accept \
                     every FerriteRuntime::variant_slug output — got \
                     None for the wire byte-string of {variant:?}"
                )
            });
            assert_eq!(
                parsed, variant,
                "FerriteRuntime::from_wire(FerriteRuntime::{variant:?}\
                 .variant_slug()) must return FerriteRuntime::{variant:?} \
                 — the (variant_slug, from_wire) pair must form a total \
                 round-trip on the closed two-arm FerriteRuntime arm-set",
            );
        }
    }

    #[test]
    fn ferrite_runtime_from_wire_rejects_unknown_byte_strings() {
        // Rejection pin on the [`FerriteRuntime::from_wire`] parser's
        // accept-set: any string outside the two-arm
        // [`FerriteRuntime::variant_slug`] output set must return
        // `None`. A future accidental widening of the accept-set (a
        // case-insensitive match that accepts `"FERRITE-SAFE"` /
        // `"Ferrite-Safe"`, a silent acceptance of the pre-lift
        // PascalCase Debug-derived shapes `"Safe"` / `"Arena"` on the
        // wire axis, a Levenshtein-forgiving arm-lookup that admits
        // `"ferrite-saf"` / `"arena"` typos, a silent absorption of the
        // sibling short-form `"safe"` / `"arena"` that the
        // caixa-lint `FixSafety::as_str` axis emits, a silent
        // absorption of the peer per-arm Go-import projection
        // [`FerriteRuntime::rt_import`] emits) would silently drift the
        // parser's accept-set from the emitter's — a downstream
        // provider-emit re-loader that bound a prior emission's
        // [`Self::variant_slug`] output back to the typed enum through
        // this parser would then bind a malformed byte-string to a
        // plausibly-wrong typed arm the caller does not route through
        // any fallback, silently misclassifying the reloaded row.
        //
        // Peer of the sibling
        // `caixa_theme::style::tests::semantic_from_wire_rejects_unknown_byte_strings`
        // (e7bca7b) /
        // `caixa_lint::diagnostic::tests::fix_safety_from_wire_rejects_unknown_byte_strings`
        // (bd505a1) /
        // `caixa_lint::diagnostic::tests::severity_from_wire_rejects_unknown_byte_strings`
        // (5afff0e) /
        // `caixa_arch::report::tests::arch_verdict_from_wire_rejects_unknown_byte_strings`
        // (6afe564) /
        // `caixa_arch::invariants::tests::invariant_kind_from_wire_rejects_unknown_byte_strings`
        // (b9e4e61) rejection pins on the peer caixa-theme / caixa-lint
        // / caixa-arch axes, and of the sibling
        // `caixa_kind_from_wire_rejects_unknown_byte_strings` (2aa6d23),
        // `caixa_dialeto_from_wire_rejects_unknown_byte_strings`
        // (d0e65ea),
        // `placement_strategy_from_wire_rejects_unknown_byte_strings`
        // (18c7342),
        // `dep_list_from_wire_returns_none_on_unknown_wire_scalar`
        // (45ee563), and
        // `path_shape_violation_from_wire_rejects_unknown_byte_strings`
        // (aebd9c6) rejection pins on the sibling caixa-core axes.
        for bad in [
            "",
            " ",
            "Safe",
            "SAFE",
            "safe",
            "Arena",
            "ARENA",
            "arena",
            "Ferrite-Safe",
            "FERRITE-SAFE",
            "Ferrite-Arena",
            "FERRITE-ARENA",
            "ferrite_safe",
            "ferrite_arena",
            "ferritesafe",
            "ferritearena",
            "ferrite-saf",
            "ferrite-aren",
            "region",
            "ferrite-region",
            "unsafe",
            "gc",
            "rt \"github.com/pleme-io/ferrite/rt\"",
            "rt \"github.com/pleme-io/ferrite/rt/arena\"",
            "ferrite-safe ",
            " ferrite-safe",
            "ferrite-safe\n",
            "ferrite-safe\t",
            "ferrite-arena ",
            " ferrite-arena",
        ] {
            assert!(
                FerriteRuntime::from_wire(bad).is_none(),
                "FerriteRuntime::from_wire({bad:?}) must return None — \
                 the parser's accept-set is exactly the two \
                 FerriteRuntime::variant_slug outputs; a widening would \
                 silently split the parser's accept-set from the \
                 emitter's arm-set",
            );
        }
    }

    #[test]
    fn ferrite_runtime_from_wire_round_trips_through_display_and_as_ref() {
        // Three-path convergence pin against the sibling
        // `(variant_slug, Display, AsRef<str>)` canonical-projection
        // triple: [`FerriteRuntime::from_wire`] must accept the byte-
        // string every path emits, so a caller that binds a prior
        // emission through any of the three paths and re-parses it
        // through the reverse projection reaches the same typed enum
        // by construction.
        //
        // A future silent detour that routes one of the three emitting
        // paths through a divergent projection (a per-arm inline
        // `match self { … }` re-inlining that opens a compile-time link
        // to the un-lifted arm-literal, a swap onto the sibling
        // [`FerriteRuntime::rt_import`] Go-import projection that would
        // collide the runtime-slug axis with the import-line axis)
        // would trip this pin under `assert_eq!` rather than at a
        // downstream re-loader's silent split.
        for &variant in FerriteRuntime::ALL {
            let via_slug = variant.variant_slug();
            let via_display = format!("{variant}");
            let via_as_ref = <FerriteRuntime as AsRef<str>>::as_ref(&variant).to_owned();
            assert_eq!(
                FerriteRuntime::from_wire(via_slug),
                Some(variant),
                "FerriteRuntime::from_wire(variant_slug) must return \
                 Some({variant:?})",
            );
            assert_eq!(
                FerriteRuntime::from_wire(&via_display),
                Some(variant),
                "FerriteRuntime::from_wire(Display) must return \
                 Some({variant:?})",
            );
            assert_eq!(
                FerriteRuntime::from_wire(&via_as_ref),
                Some(variant),
                "FerriteRuntime::from_wire(AsRef<str>) must return \
                 Some({variant:?})",
            );
        }
    }

    #[test]
    fn ferrite_runtime_try_from_str_routes_through_from_wire_accessor() {
        // Fail-before-pass-after byte-parity pin on the newly lifted
        // `impl TryFrom<&str> for FerriteRuntime` — asserts the standard-
        // library trait impl and the substrate-primitive
        // [`super::FerriteRuntime::from_wire`] `Option<Self>` accessor
        // resolve to the same two-arm accept-set across every arm the
        // exhaustive [`super::FerriteRuntime::ALL`] slice enumerates.
        // Any future silent detour that routes the trait impl through a
        // divergent projection (a per-arm inline `match s {
        // "ferrite-safe" => Ok(Self::Safe), … }` re-inlining that opens
        // a compile-time link to the un-lifted arm-literal, a silent
        // case-fold that admits `"Ferrite-Safe"` / `"FERRITE-SAFE"` and
        // would collide the canonical-lowercase accept-set the emitter
        // dispatches on, a swap onto the sibling
        // [`super::FerriteRuntime::rt_import`] Go-import projection
        // that would collide the runtime-slug axis with the import-line
        // axis) trips at caixa-provedor test time under `assert_eq!`
        // rather than at a downstream `impl TryFrom<&str>`-bound
        // consumer's silent split. Sweeps every one of the two arms
        // [`super::FerriteRuntime::ALL`] carries so no arm's projection
        // is covered only by the sibling method-named `from_wire` path.
        //
        // Peer of the sibling
        // [`caixa_core::kind::tests::caixa_kind_try_from_str_routes_through_from_wire_accessor`]
        // (3c83606),
        // [`caixa_core::dialeto::tests::caixa_dialeto_try_from_str_routes_through_from_wire_accessor`]
        // (bf33136),
        // `placement_strategy_try_from_str_routes_through_from_wire_accessor`
        // (6fd00cd),
        // `wit_shape_try_from_str_routes_through_from_wire_accessor`
        // (5472902),
        // `rate_limit_unit_try_from_str_routes_through_from_suffix_accessor`
        // (bf78400),
        // `path_shape_violation_try_from_str_routes_through_from_wire_accessor`
        // (e67e48a),
        // `caixa_arch::invariants::tests::invariant_kind_try_from_str_routes_through_from_wire_accessor`
        // (e21a857),
        // `caixa_arch::report::tests::arch_verdict_try_from_str_routes_through_from_wire_accessor`
        // (0a4cc45),
        // `caixa_lint::diagnostic::tests::severity_try_from_str_routes_through_from_wire_accessor`
        // (a7bf74c),
        // `caixa_lint::diagnostic::tests::fix_safety_try_from_str_routes_through_from_wire_accessor`
        // (df86c94), and
        // `caixa_theme::style::tests::semantic_try_from_str_routes_through_from_wire_accessor`
        // (bd7da69) — extends the trait-idiomatic reverse-projection
        // axis onto the first (and only) closed-set fieldless typed
        // enum on the caixa-provedor surface (the ferrite-runtime axis),
        // closing the fourteenth and final peer on the substrate-wide
        // reverse-projection campaign.
        for &variant in FerriteRuntime::ALL {
            let wire = variant.variant_slug();
            assert_eq!(
                <FerriteRuntime as TryFrom<&str>>::try_from(wire),
                Ok(variant),
                "TryFrom<&str> impl on FerriteRuntime must round-trip \
                 FerriteRuntime::{variant:?}.variant_slug() = {wire:?} \
                 back to Ok(FerriteRuntime::{variant:?}) — divergence \
                 from FerriteRuntime::from_wire signals a silent detour \
                 off the substrate-primitive accessor",
            );
            assert_eq!(
                <FerriteRuntime as TryFrom<&str>>::try_from(wire).ok(),
                FerriteRuntime::from_wire(wire),
                "TryFrom<&str> ok()-projection on {wire:?} must \
                 byte-equal FerriteRuntime::from_wire on the same input",
            );
        }
    }

    #[test]
    fn ferrite_runtime_try_from_str_rejects_unknown_byte_strings() {
        // Rejection witness on the `impl TryFrom<&str> for
        // FerriteRuntime` — sweeps a candidate set of byte-strings
        // outside the two-arm canonical-lowercase kebab wire accept-set
        // the sibling [`super::FerriteRuntime::variant_slug`] emits and
        // asserts every one lands on `Err(())`, so a future accidental
        // widening of the trait impl's accept-set (a stray additional
        // `_ if s.eq_ignore_ascii_case("ferrite-safe") => Ok(…)`
        // case-fold path, a silent acceptance of the pre-lift
        // PascalCase Debug-derived shapes `"Safe"` / `"Arena"` on the
        // wire axis, a Levenshtein-forgiving arm-lookup that admits
        // `"ferrite-saf"` / `"ferrite-aren"` typos, a cross-axis leak
        // that admits the sibling [`super::FerriteRuntime::rt_import`]
        // Go-import lines `"rt \"github.com/pleme-io/ferrite/rt\""` /
        // `"rt \"github.com/pleme-io/ferrite/rt/arena\""` — the exact
        // form a caller that stored `format!("{runtime}").as_str()` on
        // the wrong projection would otherwise land on) trips at
        // caixa-provedor test time. The candidate set includes the
        // empty string, whitespace-only padding, PascalCase / uppercase
        // rebrand candidates, Levenshtein-neighbor typos, snake_case
        // and no-separator variants, the trajectory-item candidate
        // `"ferrite-region"` (the intermediate `ferrite/rt/region`
        // checked-arena flavor every sibling [`FerriteRuntime`] doc
        // block already names as the next arm), the sibling
        // [`super::FerriteRuntime::rt_import`] Go-import projection
        // output on both arms, and whitespace-padded canonical tags.
        //
        // Peer of the sibling
        // `caixa_kind_try_from_str_rejects_unknown_byte_strings`
        // (3c83606),
        // `caixa_dialeto_try_from_str_rejects_unknown_byte_strings`
        // (bf33136),
        // `placement_strategy_try_from_str_rejects_unknown_byte_strings`
        // (6fd00cd),
        // `wit_shape_try_from_str_rejects_unknown_byte_strings`
        // (5472902),
        // `rate_limit_unit_try_from_str_rejects_unknown_byte_strings`
        // (bf78400),
        // `path_shape_violation_try_from_str_rejects_unknown_byte_strings`
        // (e67e48a),
        // `invariant_kind_try_from_str_rejects_unknown_byte_strings`
        // (e21a857),
        // `arch_verdict_try_from_str_rejects_unknown_byte_strings`
        // (0a4cc45),
        // `severity_try_from_str_rejects_unknown_byte_strings`
        // (a7bf74c),
        // `fix_safety_try_from_str_rejects_unknown_byte_strings`
        // (df86c94), and
        // `semantic_try_from_str_rejects_unknown_byte_strings`
        // (bd7da69) rejection pins on the sibling closed-set typed-
        // enum reverse-projection axes.
        for bad in [
            "",
            " ",
            "Safe",
            "SAFE",
            "safe",
            "Arena",
            "ARENA",
            "arena",
            "Ferrite-Safe",
            "FERRITE-SAFE",
            "Ferrite-Arena",
            "FERRITE-ARENA",
            "ferrite_safe",
            "ferrite_arena",
            "ferritesafe",
            "ferritearena",
            "ferrite-saf",
            "ferrite-aren",
            "region",
            "ferrite-region",
            "unsafe",
            "gc",
            "rt \"github.com/pleme-io/ferrite/rt\"",
            "rt \"github.com/pleme-io/ferrite/rt/arena\"",
            "ferrite-safe ",
            " ferrite-safe",
            "ferrite-safe\n",
            "ferrite-safe\t",
            "ferrite-arena ",
            " ferrite-arena",
            "?",
            "\"ferrite-safe\"",
        ] {
            assert_eq!(
                <FerriteRuntime as TryFrom<&str>>::try_from(bad),
                Err(()),
                "TryFrom<&str> impl on FerriteRuntime must reject \
                 {bad:?} — the two-arm canonical-lowercase kebab \
                 accept-set is exactly {{\"ferrite-safe\", \
                 \"ferrite-arena\"}}; a widening would silently split \
                 the trait-idiomatic axis from the sibling \
                 FerriteRuntime::from_wire resolver",
            );
        }
    }

    #[test]
    fn ferrite_runtime_try_from_str_and_from_wire_partition_the_accept_set() {
        // Cross-axis partition pin locking the newly lifted
        // `impl TryFrom<&str> for FerriteRuntime` and the substrate-
        // primitive [`super::FerriteRuntime::from_wire`] accessor to
        // the same `Option<Self>` output on every input — the two axes
        // converge on the same partition of `&str` by construction,
        // and this pin asserts that convergence directly rather than
        // only through [`super::FerriteRuntime::ALL`]'s per-arm sweep.
        // Any future divergence (a stray case-fold path on the trait
        // axis that widens acceptance past what `from_wire` admits, a
        // silent per-arm short-circuit that returns `Err(())` on an
        // input `from_wire` accepts) trips here under `assert_eq!` on
        // every input in the sweep.
        //
        // Sweeps the two accepted variant-slug outputs plus a
        // representative rejection set covering the same categories
        // the sibling
        // `ferrite_runtime_try_from_str_rejects_unknown_byte_strings`
        // pin enumerates, so a regression on either axis surfaces at
        // the partition pin rather than at a downstream consumer's
        // silent observation split.
        //
        // Peer of the sibling
        // `wit_shape_try_from_str_and_from_wire_partition_the_accept_set`
        // (5472902),
        // `restart_strategy_try_from_str_and_from_wire_partition_the_accept_set`
        // (5b828ed),
        // `restart_policy_try_from_str_and_from_wire_partition_the_accept_set`
        // (6fdd0d9), and
        // `semantic_try_from_str_and_from_wire_partition_the_accept_set`
        // (bd7da69) cross-axis partition pins on the sibling closed-
        // set typed-enum reverse-projection axes.
        let inputs: &[&str] = &[
            "ferrite-safe",
            "ferrite-arena",
            "",
            " ",
            "Safe",
            "Arena",
            "SAFE",
            "ARENA",
            "Ferrite-Safe",
            "FERRITE-SAFE",
            "ferrite_safe",
            "ferrite_arena",
            "ferritesafe",
            "ferrite-saf",
            "ferrite-region",
            "region",
            "unsafe",
            "rt \"github.com/pleme-io/ferrite/rt\"",
            "ferrite-safe ",
            " ferrite-safe",
            "?",
        ];
        for &input in inputs {
            assert_eq!(
                <FerriteRuntime as TryFrom<&str>>::try_from(input).ok(),
                FerriteRuntime::from_wire(input),
                "TryFrom<&str> and from_wire must agree on \
                 FerriteRuntime for {input:?} — the trait-idiomatic \
                 and method-named axes must partition the accept-set \
                 identically",
            );
        }
    }

    #[test]
    fn ferrite_runtime_from_into_static_str_routes_through_variant_slug_accessor() {
        // Fail-before-pass-after byte-parity pin on the newly lifted
        // `impl From<FerriteRuntime> for &'static str` — asserts the
        // standard-library trait impl and the substrate-primitive
        // [`super::FerriteRuntime::variant_slug`] `pub const fn` accessor
        // resolve to the same two-arm canonical-lowercase kebab emit-set
        // across every arm the exhaustive [`super::FerriteRuntime::ALL`]
        // slice enumerates. Any future silent detour that routes the
        // trait impl through a divergent projection (a per-arm inline
        // `match rt { Safe => "ferrite-safe", Arena => "ferrite-arena" }`
        // re-inlining that opens a compile-time link to the un-lifted
        // arm-literal outside the paired
        // [`super::FerriteRuntime::variant_slug`] dispatch, a swap onto
        // the sibling [`super::FerriteRuntime::rt_import`] Go-import
        // projection that would collide the runtime-slug axis with the
        // import-line axis, a swap onto a `format!("{:?}", …).
        // to_lowercase()` round-trip through the `#[derive(Debug)]`
        // output whose stability is *not* guaranteed and would silently
        // reroute the runtime tag through a stale byte-string with no
        // downstream signal until an operator scrolled the emit-side
        // header-comment prefix) trips at caixa-provedor test time
        // under `assert_eq!` rather than at a downstream `impl
        // Into<&'static str>`-bound consumer's silent split. Sweeps
        // every one of the two arms [`super::FerriteRuntime::ALL`]
        // carries so no arm's projection is covered only by the sibling
        // method-named `variant_slug` / [`std::fmt::Display`] /
        // [`AsRef<str>`] paths. Materializes two `<&'static str as
        // From<FerriteRuntime>>::from` outputs in `const`-shape bindings
        // against the paired [`super::FerriteRuntime::variant_slug`]
        // `pub const fn` accessor to make the `'static` lifetime promise
        // a build-time invariant — a future accidental downgrade of any
        // arm's inline canonical-lowercase kebab byte-string to a non-
        // `&'static str` (a `String::leak()`-produced return, a
        // `Box::leak`-cast, an intermediate lifetime-erasing helper)
        // trips at caixa-provedor build time rather than at a
        // downstream `'static`-bound consumer.
        //
        // Peer of the sibling
        // [`caixa_core::supervisor::tests::restart_strategy_from_into_static_str_routes_through_as_str_accessor`]
        // (523157d),
        // [`caixa_core::supervisor::tests::restart_policy_from_into_static_str_routes_through_as_str_accessor`]
        // (9fb37d0),
        // [`caixa_core::kind::tests::caixa_kind_from_into_static_str_routes_through_as_str_accessor`]
        // (edb827b),
        // [`caixa_core::dialeto::tests::caixa_dialeto_from_into_static_str_routes_through_as_str_accessor`]
        // (c189a6f),
        // [`caixa_core::aplicacao::tests::placement_strategy_from_into_static_str_routes_through_as_str_accessor`]
        // (afa3562),
        // [`caixa_core::aplicacao::tests::wit_shape_from_into_static_str_routes_through_as_str_accessor`]
        // (56998ec),
        // [`caixa_core::aplicacao::tests::rate_limit_unit_from_into_static_str_routes_through_as_suffix_accessor`]
        // (7fdfbf4),
        // [`caixa_core::render::tests::path_shape_violation_from_into_static_str_routes_through_as_str_accessor`]
        // (070a6de),
        // `caixa_arch::invariants::tests::invariant_kind_from_into_static_str_routes_through_as_str_accessor`
        // (f2ca7bc),
        // `caixa_arch::report::tests::arch_verdict_from_into_static_str_routes_through_as_str_accessor`
        // (d4559cb),
        // `caixa_lint::diagnostic::tests::severity_from_into_static_str_routes_through_as_str_accessor`
        // (5cc3b8b),
        // `caixa_lint::diagnostic::tests::fix_safety_from_into_static_str_routes_through_as_str_accessor`
        // (2a56127), and
        // `caixa_theme::style::tests::semantic_from_into_static_str_routes_through_as_str_accessor`
        // (07f36bb) pins on the sibling closed-set typed-enum forward-
        // projection axes — closes the trait-idiomatic forward-projection
        // axis on the last (and only) closed-set fieldless typed enum on
        // the caixa-provedor surface (the ferrite-runtime axis) and the
        // fourteenth and final peer on the substrate-wide forward-
        // projection campaign.
        const SAFE: &str = FerriteRuntime::Safe.variant_slug();
        const ARENA: &str = FerriteRuntime::Arena.variant_slug();
        for &variant in FerriteRuntime::ALL {
            let via_trait: &'static str = <&'static str as From<FerriteRuntime>>::from(variant);
            let via_method: &'static str = variant.variant_slug();
            assert_eq!(
                via_trait, via_method,
                "From<FerriteRuntime> for &'static str impl must \
                 round-trip FerriteRuntime::{variant:?} to the same \
                 canonical-lowercase kebab byte-string \
                 FerriteRuntime::variant_slug returns — divergence \
                 signals a silent detour off the substrate-primitive \
                 accessor"
            );
            let via_into: &'static str = variant.into();
            assert_eq!(
                via_into, via_method,
                "Into<&'static str>::into on FerriteRuntime::{variant:?} \
                 must byte-equal FerriteRuntime::variant_slug on the \
                 same input — the blanket-derived Into shape must \
                 resolve to the same variant_slug dispatch as the \
                 explicit From impl"
            );
        }
        assert_eq!(
            [SAFE, ARENA],
            ["ferrite-safe", "ferrite-arena"],
            "const-context FerriteRuntime::variant_slug must resolve to \
             the canonical-lowercase kebab byte-strings — a future \
             accidental downgrade of any arm to a non-const or non-\
             static byte-string breaks the `&'static str`-lifetime \
             promise the paired From<FerriteRuntime> for &'static str \
             impl carries by construction"
        );
    }

    #[test]
    fn ferrite_runtime_from_into_static_str_and_variant_slug_partition_the_emit_set() {
        // Cross-axis partition pin: the paired trait-idiomatic
        // `From<FerriteRuntime> for &'static str` forward projection and
        // the method-named [`super::FerriteRuntime::variant_slug`]
        // forward projection must resolve identically on *every* arm,
        // not just the ones named in the primary byte-parity pin above.
        // Sweeps every [`super::FerriteRuntime::ALL`] arm and asserts
        // the trait's `From::from` output byte-equals the method-named
        // accessor's return-value on each, locking the two forward-
        // projection paths together by construction so any future
        // detour (a stray `From` special-case that lands on a divergent
        // per-arm literal outside the paired `variant_slug` dispatch, a
        // hypothetical rebrand touching one axis without the other, a
        // silent swap onto the sibling
        // [`super::FerriteRuntime::rt_import`] Go-import projection
        // that would collide the runtime-slug axis with the import-line
        // axis) trips at caixa-provedor test time.
        //
        // Peer of the sibling forward-projection partition pins
        // [`caixa_core::supervisor::tests::restart_strategy_from_into_static_str_and_as_str_partition_the_emit_set`]
        // (523157d),
        // [`caixa_core::supervisor::tests::restart_policy_from_into_static_str_and_as_str_partition_the_emit_set`]
        // (9fb37d0),
        // [`caixa_core::kind::tests::caixa_kind_from_into_static_str_and_as_str_partition_the_emit_set`]
        // (edb827b),
        // [`caixa_core::dialeto::tests::caixa_dialeto_from_into_static_str_and_as_str_partition_the_emit_set`]
        // (c189a6f),
        // [`caixa_core::aplicacao::tests::placement_strategy_from_into_static_str_and_as_str_partition_the_emit_set`]
        // (afa3562),
        // [`caixa_core::aplicacao::tests::wit_shape_from_into_static_str_and_as_str_partition_the_emit_set`]
        // (56998ec),
        // [`caixa_core::aplicacao::tests::rate_limit_unit_from_into_static_str_and_as_suffix_partition_the_emit_set`]
        // (7fdfbf4),
        // [`caixa_core::render::tests::path_shape_violation_from_into_static_str_and_as_str_partition_the_emit_set`]
        // (070a6de),
        // `caixa_arch::invariants::tests::invariant_kind_from_into_static_str_and_as_str_partition_the_emit_set`
        // (f2ca7bc),
        // `caixa_arch::report::tests::arch_verdict_from_into_static_str_and_as_str_partition_the_emit_set`
        // (d4559cb),
        // `caixa_lint::diagnostic::tests::severity_from_into_static_str_and_as_str_partition_the_emit_set`
        // (5cc3b8b),
        // `caixa_lint::diagnostic::tests::fix_safety_from_into_static_str_and_as_str_partition_the_emit_set`
        // (2a56127), and
        // `caixa_theme::style::tests::semantic_from_into_static_str_and_as_str_partition_the_emit_set`
        // (07f36bb) — closes the round-trip discipline on the last
        // closed-set fieldless typed enum in the caixa workspace,
        // closing the two-way `Self ↔ &'static str` round-trip on the
        // trait-idiomatic pair (`From<Self> for &'static str` +
        // `TryFrom<&str> for Self`) as well as the pre-existing method-
        // named pair (`variant_slug` + `from_wire`).
        for &variant in FerriteRuntime::ALL {
            let via_trait: &'static str = <&'static str as From<FerriteRuntime>>::from(variant);
            let via_method: &'static str = variant.variant_slug();
            assert_eq!(
                via_trait, via_method,
                "From<FerriteRuntime> for &'static str and \
                 FerriteRuntime::variant_slug must resolve identically \
                 on FerriteRuntime::{variant:?} — divergence signals the \
                 two forward-projection paths have drifted onto different \
                 emit-sets"
            );
        }
        // Round-trip witness: every arm's forward `From` output re-parses
        // through the paired trait-idiomatic `TryFrom<&str>` back to the
        // original variant. Closes the two-way `FerriteRuntime ↔ &'static str`
        // round-trip on the trait-idiomatic axis pair directly (no wire-
        // vocab intermediate — the emit-side
        // [`super::FerriteRuntime::variant_slug`] and the parse-side
        // [`super::FerriteRuntime::from_wire`] dispatch on the same two
        // inline canonical-lowercase kebab byte-strings by construction,
        // so round-tripping through the paired `From<Self> for &'static str`
        // + `TryFrom<&str> for Self` trait impls composes to the identity
        // on `FerriteRuntime::ALL`).
        for &variant in FerriteRuntime::ALL {
            let emitted: &'static str = <&'static str as From<FerriteRuntime>>::from(variant);
            let reparsed =
                <FerriteRuntime as TryFrom<&str>>::try_from(emitted).unwrap_or_else(|()| {
                    panic!(
                        "TryFrom<&str> for FerriteRuntime must accept \
                         every From<FerriteRuntime> for &'static str \
                         output — got Err(()) for \
                         FerriteRuntime::{variant:?}'s emit byte-string \
                         {emitted:?}"
                    )
                });
            assert_eq!(
                reparsed, variant,
                "trait-idiomatic FerriteRuntime ↔ &'static str \
                 round-trip must be the identity on \
                 FerriteRuntime::{variant:?} — the From<Self> for \
                 &'static str + TryFrom<&str> for Self pair must compose \
                 to the identity on the closed two-arm accept-set"
            );
        }
    }

    #[test]
    fn ferrite_runtime_from_borrowed_into_static_str_routes_through_variant_slug_accessor() {
        // Fail-before-pass-after byte-parity pin on the newly lifted
        // `impl From<&FerriteRuntime> for &'static str` — asserts the
        // borrowed-input standard-library trait impl and the substrate-
        // primitive [`super::FerriteRuntime::variant_slug`] `pub const
        // fn` accessor resolve to the same two-arm canonical-lowercase
        // kebab emit-set across every arm the exhaustive
        // [`super::FerriteRuntime::ALL`] slice enumerates. Rust's
        // `From` trait does not auto-derive the borrowed-input sibling
        // from a paired owned-input impl (no `impl<T, U> From<&T> for
        // U where T: Copy, U: From<T>` blanket in `core`), so the
        // borrowed-input axis is a distinct trait-idiomatic surface
        // that a `.iter().map(Into::into)` shape over
        // [`super::FerriteRuntime::ALL`] (whose iterator yields
        // `&FerriteRuntime`, not `FerriteRuntime`) reaches through
        // this impl and no other — the paired owned-input
        // [`From<FerriteRuntime>`] impl requires an explicit
        // `.copied()` / dereference before the trait fires.
        // Materializes the `<&'static str as
        // From<&FerriteRuntime>>::from` output in two `const`-shape
        // bindings against the paired
        // [`super::FerriteRuntime::variant_slug`] `pub const fn`
        // accessor to make the `'static` lifetime promise a build-time
        // invariant — a future accidental downgrade of any arm's
        // inline canonical-lowercase kebab byte-string to a non-
        // `&'static str` (a `String::leak()`-produced return, a
        // `Box::leak`-cast, an intermediate lifetime-erasing helper)
        // trips at caixa-provedor build time rather than at a
        // downstream `'static`-bound consumer.
        //
        // Peer of the sibling
        // `caixa_lint::diagnostic::tests::fix_safety_from_borrowed_into_static_str_routes_through_as_str_accessor`
        // (d8769ab),
        // `caixa_lint::diagnostic::tests::severity_from_borrowed_into_static_str_routes_through_as_str_accessor`
        // (2b9003f),
        // `caixa_arch::report::tests::arch_verdict_from_borrowed_into_static_str_routes_through_as_str_accessor`
        // (73bda50), and
        // `caixa_arch::invariants::tests::invariant_kind_from_borrowed_into_static_str_routes_through_as_str_accessor`
        // (238d886) pins on the peer outside-`caixa-core` closed-set-
        // enum borrowed-input `&'static str`-returning axes.
        const SAFE: &str = FerriteRuntime::Safe.variant_slug();
        const ARENA: &str = FerriteRuntime::Arena.variant_slug();
        for variant in FerriteRuntime::ALL {
            let via_trait: &'static str = <&'static str as From<&FerriteRuntime>>::from(variant);
            let via_method: &'static str = variant.variant_slug();
            assert_eq!(
                via_trait, via_method,
                "From<&FerriteRuntime> for &'static str impl must \
                 round-trip &FerriteRuntime::{variant:?} to the same \
                 canonical-lowercase kebab byte-string \
                 FerriteRuntime::variant_slug returns — divergence \
                 signals a silent detour off the substrate-primitive \
                 accessor"
            );
            let via_into: &'static str = variant.into();
            assert_eq!(
                via_into, via_method,
                "Into<&'static str>::into on &FerriteRuntime::{variant:?} \
                 must byte-equal FerriteRuntime::variant_slug on the \
                 same input — the blanket-derived Into shape must \
                 resolve to the same variant_slug dispatch as the \
                 explicit From impl"
            );
        }
        assert_eq!(
            [SAFE, ARENA],
            ["ferrite-safe", "ferrite-arena"],
            "const-context FerriteRuntime::variant_slug must resolve to \
             the two canonical-lowercase kebab byte-strings — the \
             borrowed-input From<&FerriteRuntime> for &'static str impl \
             inherits its `'static` lifetime promise from the same \
             accessor the owned-input sibling routes through"
        );
    }

    #[test]
    fn ferrite_runtime_from_owned_and_borrowed_into_static_str_agree_on_every_arm() {
        // Cross-axis partition pin: the paired trait-idiomatic
        // owned-input `From<FerriteRuntime> for &'static str` and
        // borrowed-input `From<&FerriteRuntime> for &'static str`
        // (this lift) forward projections must resolve identically on
        // every arm, locking the two input-shape paths together so any
        // future detour (a stray borrowed-input special-case that
        // lands on a divergent per-arm literal outside the paired
        // `variant_slug` dispatch, a hypothetical rebrand touching one
        // axis without the other) trips at caixa-provedor test time.
        // Then a witness that a `.iter().map(Into::into)` pipe over
        // [`super::FerriteRuntime::ALL`] (whose iterator yields
        // `&FerriteRuntime`) materializes the two-arm accept-set
        // through the borrowed-input axis alone — the exact shape a
        // future M4 admission-webhook rejection body composer, a
        // future `feira publish-provider --list-runtimes` CLI
        // enumeration verb, or a future
        // `HashMap::<&'static str, super::FerriteRuntime>::from_iter(
        //     super::FerriteRuntime::ALL.iter().map(|rt| (rt.into(), *rt)))`-
        // style per-runtime-tier lookup reaches through — closing the
        // two-way owned/borrowed input-shape symmetry on the forward-
        // projection trait-idiomatic axis.
        //
        // Peer of the sibling
        // `caixa_lint::diagnostic::tests::fix_safety_from_owned_and_borrowed_into_static_str_agree_on_every_arm`
        // (d8769ab),
        // `caixa_lint::diagnostic::tests::severity_from_owned_and_borrowed_into_static_str_agree_on_every_arm`
        // (2b9003f),
        // `caixa_arch::report::tests::arch_verdict_from_owned_and_borrowed_into_static_str_agree_on_every_arm`
        // (73bda50), and
        // `caixa_arch::invariants::tests::invariant_kind_from_owned_and_borrowed_into_static_str_agree_on_every_arm`
        // (238d886) partition pins on the peer outside-`caixa-core`
        // closed-set-enum borrowed-input `&'static str`-returning
        // axes.
        for &variant in FerriteRuntime::ALL {
            let via_owned: &'static str = <&'static str as From<FerriteRuntime>>::from(variant);
            let via_borrowed: &'static str =
                <&'static str as From<&FerriteRuntime>>::from(&variant);
            assert_eq!(
                via_owned, via_borrowed,
                "owned-input From<FerriteRuntime> for &'static str and \
                 borrowed-input From<&FerriteRuntime> for &'static str \
                 must resolve identically on FerriteRuntime::{variant:?} \
                 — divergence signals the two input-shape paths have \
                 drifted onto different emit-sets"
            );
        }
        // `.iter().map(Into::into)` pipe witness: the standard-library
        // iterator over `&'static [FerriteRuntime]` yields
        // `&FerriteRuntime`, so this pipe fires through the borrowed-
        // input axis alone. Any future accidental removal or shadowing
        // of the borrowed-input impl would break the pipe at compile
        // time rather than silently re-route through the paired
        // owned-input axis after a `.copied()` / [`Copy`]-bound
        // dereference restatement.
        let via_pipe: Vec<&'static str> = FerriteRuntime::ALL.iter().map(Into::into).collect();
        let via_variant_slug: Vec<&'static str> = FerriteRuntime::ALL
            .iter()
            .map(|rt| rt.variant_slug())
            .collect();
        assert_eq!(
            via_pipe, via_variant_slug,
            "`.iter().map(Into::into)` pipe over FerriteRuntime::ALL \
             must byte-equal `.iter().map(FerriteRuntime::variant_slug)` \
             on the two-arm accept-set — the borrowed-input \
             From<&FerriteRuntime> for &'static str axis is what routes \
             the pipe through the substrate-primitive accessor without a \
             spurious Copy deref"
        );
    }

    #[test]
    fn ferrite_runtime_from_into_owned_string_routes_through_variant_slug_accessor() {
        // Fail-before-pass-after byte-parity pin on the newly lifted
        // `impl From<FerriteRuntime> for String` — asserts the owned-
        // `String`-returning standard-library trait impl and the
        // substrate-primitive [`super::FerriteRuntime::variant_slug`]
        // `pub const fn` accessor resolve to the same two-arm
        // canonical-lowercase kebab emit-set across every arm the
        // exhaustive [`super::FerriteRuntime::ALL`] slice enumerates.
        // Rust's standard library does not carry a blanket
        // `impl<T: AsRef<str>> From<T> for String`, so the owned-
        // `String` axis is a distinct trait-idiomatic surface that a
        // `let key: String = runtime.into();`-shaped downstream call
        // site reaches through this impl and no other — the sibling
        // `&'static str`-returning axes force an explicit
        // `.to_owned()` / [`String::from`] restatement whose type
        // bounds have no compile-time link to the substrate primitive.
        // Sweeps every one of the two arms
        // [`super::FerriteRuntime::ALL`] carries so no arm's
        // projection is covered only by the sibling method-named
        // `variant_slug` / [`std::fmt::Display`] / [`AsRef<str>`] /
        // owned-input `&'static str`-returning paths.
        //
        // Peer of the sibling
        // `caixa_arch::report::tests::arch_verdict_from_into_owned_string_routes_through_as_str_accessor`
        // (cc80a53 — paired verdict-outcome axis on the sibling
        // caixa-arch closed-set enum),
        // `caixa_arch::invariants::tests::invariant_kind_from_into_owned_string_routes_through_as_str_accessor`
        // (1afd8d5 — first outside-`caixa-core` arm on the owned-
        // `String` axis, the paired severity-classification axis on
        // the sibling caixa-arch closed-set enum),
        // `caixa_lint::diagnostic::tests::severity_from_into_owned_string_routes_through_as_str_accessor`
        // (4635d4e), and
        // `caixa_lint::diagnostic::tests::fix_safety_from_into_owned_string_routes_through_as_str_accessor`
        // (e4d73c6) pins on the peer outside-`caixa-core` closed-set-
        // enum owned-`String`-returning axes — extends the trait-
        // idiomatic owned-`String`-returning forward-projection family
        // onto the sole closed-set fieldless typed enum on the caixa-
        // provedor surface (the ferrite-runtime two-arm axis).
        for &variant in FerriteRuntime::ALL {
            let via_trait: String = <String as From<FerriteRuntime>>::from(variant);
            let via_method: &'static str = variant.variant_slug();
            assert_eq!(
                via_trait.as_str(),
                via_method,
                "From<FerriteRuntime> for String impl must round-trip \
                 FerriteRuntime::{variant:?} to the same canonical-\
                 lowercase kebab byte-string \
                 FerriteRuntime::variant_slug returns — divergence \
                 signals a silent detour off the substrate-primitive \
                 accessor"
            );
            let via_into: String = variant.into();
            assert_eq!(
                via_into.as_str(),
                via_method,
                "Into<String>::into on FerriteRuntime::{variant:?} \
                 must byte-equal FerriteRuntime::variant_slug on the \
                 same input — the blanket-derived Into shape must \
                 resolve to the same variant_slug dispatch as the \
                 explicit From impl"
            );
        }
    }

    #[test]
    fn ferrite_runtime_from_into_owned_string_and_static_str_agree_on_every_arm() {
        // Cross-axis partition pin: the paired trait-idiomatic
        // owned-input `&'static str`-returning
        // `From<FerriteRuntime> for &'static str` and owned-`String`-
        // returning `From<FerriteRuntime> for String` (this lift)
        // forward projections must resolve identically on every arm,
        // locking the two output-shape paths together so any future
        // detour (a stray owned-`String` special-case that lands on a
        // divergent per-arm literal outside the paired `variant_slug`
        // dispatch, a hypothetical rebrand touching one axis without
        // the other, a silent swap onto the sibling
        // [`super::FerriteRuntime::rt_import`] Go-import projection
        // that would collide the runtime-slug axis with the import-
        // line axis) trips at caixa-provedor test time. Then a
        // witness that the `ToString::to_string`-through-
        // [`std::fmt::Display`] surface (`variant.to_string()`) byte-
        // equals the trait-idiomatic owned-`String` axis
        // (`String::from(variant)`) on every arm, so a future consumer
        // that reaches for `.to_string()` and one that reaches for
        // `.into::<String>()` land on the same substrate-primitive
        // vocabulary. Plus a `.iter().copied().map(String::from)` pipe
        // witness over [`super::FerriteRuntime::ALL`] — the exact
        // shape a future per-runtime histogram key materializer or
        // admission-webhook rejection body composer reaches through —
        // materializes the two-arm accept-set through the owned-
        // `String` axis alone. Plus a direct `Self → String → Self`
        // round-trip witness through the paired [`TryFrom<&str>`]
        // axis on the owned-`String`'s [`String::as_str`] borrow,
        // closing the two-way round-trip on the owned-`String` axis
        // directly (no wire-vocab intermediate — the emit-side
        // [`super::FerriteRuntime::variant_slug`] and the parse-side
        // [`super::FerriteRuntime::from_wire`] dispatch on the same
        // two inline canonical-lowercase kebab byte-strings by
        // construction).
        //
        // Peer of the sibling
        // `caixa_arch::report::tests::arch_verdict_from_into_owned_string_and_static_str_agree_on_every_arm`
        // (cc80a53) partition pin on the sibling caixa-arch closed-
        // set enum.
        for &variant in FerriteRuntime::ALL {
            let owned_string: String = <String as From<FerriteRuntime>>::from(variant);
            let owned_static: &'static str = <&'static str as From<FerriteRuntime>>::from(variant);
            assert_eq!(
                owned_string.as_str(),
                owned_static,
                "From<FerriteRuntime> for String and \
                 From<FerriteRuntime> for &'static str must resolve \
                 identically on FerriteRuntime::{variant:?} — \
                 divergence signals the two output-shape forward-\
                 projection paths have drifted onto different emit-\
                 sets"
            );
            let via_display: String = variant.to_string();
            assert_eq!(
                owned_string, via_display,
                "From<FerriteRuntime> for String and ToString::\
                 to_string via Display must resolve identically on \
                 FerriteRuntime::{variant:?} — divergence signals the \
                 trait-idiomatic owned-`String` axis and the Display-\
                 routed ToString axis have drifted onto different \
                 vocabularies"
            );
        }
        let via_iter: Vec<String> = FerriteRuntime::ALL
            .iter()
            .copied()
            .map(String::from)
            .collect();
        let via_method: Vec<String> = FerriteRuntime::ALL
            .iter()
            .map(|rt| rt.variant_slug().to_owned())
            .collect();
        assert_eq!(
            via_iter, via_method,
            "`.iter().copied().map(String::from)` over \
             FerriteRuntime::ALL must byte-equal \
             `.iter().map(|rt| rt.variant_slug().to_owned())` on every \
             arm — the owned-`String` `From<FerriteRuntime> for \
             String` axis is what makes the `.map(String::from)` \
             shape route through the substrate-primitive \
             `FerriteRuntime::variant_slug` accessor rather than \
             through a per-call-site `.to_owned()` / \
             `String::from(runtime.variant_slug())` detour"
        );
        for &variant in FerriteRuntime::ALL {
            let emitted: String = variant.into();
            let re_parsed: Option<FerriteRuntime> =
                <FerriteRuntime as TryFrom<&str>>::try_from(emitted.as_str()).ok();
            assert_eq!(
                re_parsed,
                Some(variant),
                "trait-idiomatic owned-`String` axis pair must round-\
                 trip FerriteRuntime::{variant:?} through \
                 `.into::<String>()` and back through \
                 `TryFrom<&str>` on the owned-`String`'s \
                 `String::as_str` borrow — a break signals the \
                 forward-emit owned-`String` axis and the reverse-\
                 parse `TryFrom<&str>` axis have drifted onto \
                 different vocabularies"
            );
        }
    }
}
