//! Ferrite runtime flavor + import helpers.

/// Which ferrite runtime to target at emit time.
///
/// `Safe` → `ferrite/rt` (checked types, GC-compatible). The same binary
/// passes `ferrite-check` and can later be swapped to `Arena` via
/// `ferrite-mutate`.
///
/// `Arena` → `ferrite/rt/arena` (mmap regions, zero-GC). Final form.
///
/// The [`gen_platform::IsVariant`] derive emits per-arm
/// [`FerriteRuntime::is_safe`] / [`FerriteRuntime::is_arena`] predicates
/// every downstream ferrite-runtime-family gate keys off — the same
/// closed-set arm-discriminator discipline the sibling
/// `caixa_core::CaixaKind` / `caixa_core::CaixaDialeto` /
/// `caixa_core::PlacementStrategy` / `caixa_core::RestartStrategy` /
/// `caixa_core::RestartPolicy` / `caixa_core::DepList` /
/// `caixa_core::RateLimitUnit` / `caixa_core::render::PathShapeViolation`
/// / `caixa_arch::InvariantKind` / `caixa_arch::ArchVerdict` /
/// `caixa_lint::FixSafety` / `caixa_lint::Severity` closed-set fieldless
/// typed enums already carry. `Hash` joins the derive set so the enum
/// can live in arm-keyed sets (a future `feira publish-provider
/// --runtime-policy=<tier>` verb keying arm-specific counters, a future
/// admission-webhook rejection body naming the accepted runtime flavors).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, gen_platform::IsVariant)]
pub enum FerriteRuntime {
    Safe,
    Arena,
}

impl FerriteRuntime {
    /// Exhaustive iteration surface for every consumer that walks the
    /// closed two-arm [`FerriteRuntime`] discriminator set (the
    /// byte-parity witness against the paired [`gen_platform::IsVariant`]-
    /// derived [`Self::is_safe`] / [`Self::is_arena`] predicate family, a
    /// future `feira publish-provider --list-runtimes` CLI enumeration of
    /// the accepted runtime tags, a future admission-webhook rejection
    /// body naming the accepted runtime set, any future round-trip fuzz
    /// harness that sweeps every arm).
    ///
    /// A future variant addition (a `Region` tier between [`Self::Safe`]
    /// and [`Self::Arena`] for the intermediate `ferrite/rt/region`
    /// checked-arena flavor the ferrite roadmap grows) extends this
    /// slice as a single edit and every consumer picks up the new entry
    /// by construction; the compiler-checked exhaustiveness on the
    /// paired [`gen_platform::IsVariant`]-derived per-arm predicates
    /// covers the projection axis so both halves of the closed-set
    /// discipline migrate as one edit.
    ///
    /// Peer of the sibling closed-set fieldless typed enums'
    /// [`caixa_core::CaixaKind::ALL`] / [`caixa_core::CaixaDialeto::ALL`]
    /// / [`caixa_core::aplicacao::PlacementStrategy::ALL`] /
    /// [`caixa_core::supervisor::RestartStrategy::ALL`] /
    /// [`caixa_core::supervisor::RestartPolicy::ALL`] /
    /// [`caixa_core::dep::DepList::ALL`] /
    /// [`caixa_core::aplicacao::RateLimitUnit::ALL`] /
    /// [`caixa_core::render::PathShapeViolation::ALL`] /
    /// [`caixa_arch::invariants::InvariantKind::ALL`] /
    /// [`caixa_arch::report::ArchVerdict::ALL`] /
    /// [`caixa_lint::FixSafety::ALL`] / [`caixa_lint::Severity::ALL`]
    /// exhaustive-iteration surfaces — the thirteenth closed-set typed
    /// enum on the caixa surface (and the first inside `caixa-provedor`)
    /// to converge onto the same one-canonical-arm-list-per-enum
    /// discipline. Order matches variant declaration order verbatim
    /// (`Safe` → `Arena`).
    pub const ALL: &'static [Self] = &[Self::Safe, Self::Arena];

    /// Per-arm Go-import projection: the exact `rt "…"` line the
    /// ferrite-typed emit prepends inside its `import (…)` block. The
    /// canonical projection every ferrite-runtime-family consumer keys
    /// off — one typed dispatch on the substrate primitive replaces the
    /// pre-lift per-arm inline match at the two open-coded call sites
    /// [`crate::backend::emit_go_resource`] previously carried through
    /// the free-function [`ferrite_rt_import`] wrapper.
    #[must_use]
    pub const fn rt_import(self) -> &'static str {
        match self {
            Self::Safe => "rt \"github.com/pleme-io/ferrite/rt\"",
            Self::Arena => "rt \"github.com/pleme-io/ferrite/rt/arena\"",
        }
    }

    /// Short runtime-slug the emit-side burns into the generated
    /// file's header comment (`// Code generated by caixa-provedor
    /// (<variant-slug>). DO NOT EDIT.`). The canonical projection
    /// every ferrite-runtime-slug consumer keys off — one typed
    /// dispatch on the substrate primitive replaces the pre-lift
    /// per-arm inline match at [`crate::backend::emit_go_resource`]
    /// previously routed through the free-function
    /// [`ferrite_runtime_variant`] wrapper.
    #[must_use]
    pub const fn variant_slug(self) -> &'static str {
        match self {
            Self::Safe => "ferrite-safe",
            Self::Arena => "ferrite-arena",
        }
    }
}

/// Free-function wrapper preserved for the crate-level `pub use`
/// re-export in [`crate`]; routes through the substrate-primitive
/// method [`FerriteRuntime::rt_import`].
#[must_use]
pub fn ferrite_rt_import(runtime: FerriteRuntime) -> &'static str {
    runtime.rt_import()
}

/// Free-function wrapper preserved for the crate-level `pub use`
/// re-export in [`crate`]; routes through the substrate-primitive
/// method [`FerriteRuntime::variant_slug`].
#[must_use]
pub const fn ferrite_runtime_variant(runtime: FerriteRuntime) -> &'static str {
    runtime.variant_slug()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ferrite_runtime_all_lists_every_variant_in_declaration_order() {
        // Fail-before-pass-after pin on the [`gen_platform::IsVariant`]
        // derive's per-arm-list-per-enum discipline for
        // [`FerriteRuntime`]: any future variant addition (a `Region`
        // tier between [`FerriteRuntime::Safe`] and
        // [`FerriteRuntime::Arena`] for the intermediate
        // `ferrite/rt/region` checked-arena flavor the ferrite roadmap
        // grows) that lands the new variant on the enum without
        // extending [`FerriteRuntime::ALL`] trips this test — the
        // compiler-checked exhaustiveness on the paired
        // [`gen_platform::IsVariant`]-derived per-arm predicates
        // ([`FerriteRuntime::is_safe`] / [`FerriteRuntime::is_arena`])
        // covers the projection axis; this pin covers the
        // exhaustive-iteration axis so both halves of the closed-set
        // discipline migrate as one edit.
        assert_eq!(
            FerriteRuntime::ALL,
            &[FerriteRuntime::Safe, FerriteRuntime::Arena],
        );
        // Every arm satisfies exactly one of the paired per-arm
        // predicates — the byte-parity pin between the
        // [`FerriteRuntime::ALL`] iteration axis and the per-arm
        // [`gen_platform::IsVariant`]-derived predicate axis.
        for arm in FerriteRuntime::ALL {
            assert_eq!(
                usize::from(arm.is_safe()) + usize::from(arm.is_arena()),
                1,
                "FerriteRuntime::{arm:?} must satisfy exactly one of \
                 is_safe / is_arena",
            );
        }
    }

    #[test]
    fn ferrite_runtime_predicates_are_byte_equal_to_matches_family() {
        // Fail-before-pass-after pin on the two-arm convergence of the
        // pre-lift per-arm inline `match (runtime) { Safe => …, Arena
        // => … }` sites the two free-function projections
        // ([`ferrite_rt_import`], [`ferrite_runtime_variant`]) carried
        // onto the [`gen_platform::IsVariant`]-derive-generated per-arm
        // predicate family: for every arm, each predicate agrees
        // byte-for-byte with the pre-lift `matches!(_,
        // FerriteRuntime::…)` shape.
        //
        // A future rebrand touching either endpoint (a
        // `#[is_variant(name = "…")]` attribute drift on the derive, an
        // arm rename, an accidental peer predicate that shadows the
        // derive-generated one) would silently split the two paths and
        // trip this pin.
        for arm in FerriteRuntime::ALL {
            assert_eq!(
                arm.is_safe(),
                matches!(arm, FerriteRuntime::Safe),
                "FerriteRuntime::{arm:?}.is_safe() must agree with \
                 matches!(_, FerriteRuntime::Safe) byte-for-byte",
            );
            assert_eq!(
                arm.is_arena(),
                matches!(arm, FerriteRuntime::Arena),
                "FerriteRuntime::{arm:?}.is_arena() must agree with \
                 matches!(_, FerriteRuntime::Arena) byte-for-byte",
            );
        }
    }

    #[test]
    fn ferrite_runtime_projections_are_stable_per_arm_across_all() {
        // Accessor-level byte-parity pin: for every arm in
        // [`FerriteRuntime::ALL`], both projections
        // ([`FerriteRuntime::rt_import`] / [`FerriteRuntime::variant_slug`])
        // return the exact byte-string the pre-lift free-function form
        // ([`ferrite_rt_import`] / [`ferrite_runtime_variant`]) emitted.
        // This pin guards against a future silent split between the
        // free-function wrappers, the inherent-method projections, and
        // the two open-coded emit-side call sites in
        // [`crate::backend::emit_go_resource`] — any drift on the
        // canonical per-arm byte-string surfaces as a test failure
        // here rather than at downstream `go build` or `ferrite-check`
        // time.
        for arm in FerriteRuntime::ALL {
            assert_eq!(arm.rt_import(), ferrite_rt_import(*arm));
            assert_eq!(arm.variant_slug(), ferrite_runtime_variant(*arm));
        }
        // Pin the exact byte-shapes so a future rebrand of either the
        // `rt "…"` line or the header-comment slug surfaces here.
        assert_eq!(
            FerriteRuntime::Safe.rt_import(),
            "rt \"github.com/pleme-io/ferrite/rt\"",
        );
        assert_eq!(
            FerriteRuntime::Arena.rt_import(),
            "rt \"github.com/pleme-io/ferrite/rt/arena\"",
        );
        assert_eq!(FerriteRuntime::Safe.variant_slug(), "ferrite-safe");
        assert_eq!(FerriteRuntime::Arena.variant_slug(), "ferrite-arena");
    }
}
