//! Ferrite runtime flavor + import helpers.

/// Which ferrite runtime to target at emit time.
///
/// `Safe` → `ferrite/rt` (checked types, GC-compatible). The same binary
/// passes `ferrite-check` and can later be swapped to `Arena` via
/// `ferrite-mutate`.
///
/// `Arena` → `ferrite/rt/arena` (mmap regions, zero-GC). Final form.
///
/// The [`gen_platform::IsVariant`] derive emits per-arm
/// [`FerriteRuntime::is_safe`] / [`FerriteRuntime::is_arena`] predicates
/// every downstream ferrite-runtime-family gate keys off — the same
/// closed-set arm-discriminator discipline the sibling
/// `caixa_core::CaixaKind` / `caixa_core::CaixaDialeto` /
/// `caixa_core::PlacementStrategy` / `caixa_core::RestartStrategy` /
/// `caixa_core::RestartPolicy` / `caixa_core::DepList` /
/// `caixa_core::RateLimitUnit` / `caixa_core::render::PathShapeViolation`
/// / `caixa_arch::InvariantKind` / `caixa_arch::ArchVerdict` /
/// `caixa_lint::FixSafety` / `caixa_lint::Severity` closed-set fieldless
/// typed enums already carry. `Hash` joins the derive set so the enum
/// can live in arm-keyed sets (a future `feira publish-provider
/// --runtime-policy=<tier>` verb keying arm-specific counters, a future
/// admission-webhook rejection body naming the accepted runtime flavors).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, gen_platform::IsVariant)]
pub enum FerriteRuntime {
    Safe,
    Arena,
}

impl FerriteRuntime {
    /// Exhaustive iteration surface for every consumer that walks the
    /// closed two-arm [`FerriteRuntime`] discriminator set (the
    /// byte-parity witness against the paired [`gen_platform::IsVariant`]-
    /// derived [`Self::is_safe`] / [`Self::is_arena`] predicate family, a
    /// future `feira publish-provider --list-runtimes` CLI enumeration of
    /// the accepted runtime tags, a future admission-webhook rejection
    /// body naming the accepted runtime set, any future round-trip fuzz
    /// harness that sweeps every arm).
    ///
    /// A future variant addition (a `Region` tier between [`Self::Safe`]
    /// and [`Self::Arena`] for the intermediate `ferrite/rt/region`
    /// checked-arena flavor the ferrite roadmap grows) extends this
    /// slice as a single edit and every consumer picks up the new entry
    /// by construction; the compiler-checked exhaustiveness on the
    /// paired [`gen_platform::IsVariant`]-derived per-arm predicates
    /// covers the projection axis so both halves of the closed-set
    /// discipline migrate as one edit.
    ///
    /// Peer of the sibling closed-set fieldless typed enums'
    /// [`caixa_core::CaixaKind::ALL`] / [`caixa_core::CaixaDialeto::ALL`]
    /// / [`caixa_core::aplicacao::PlacementStrategy::ALL`] /
    /// [`caixa_core::supervisor::RestartStrategy::ALL`] /
    /// [`caixa_core::supervisor::RestartPolicy::ALL`] /
    /// [`caixa_core::dep::DepList::ALL`] /
    /// [`caixa_core::aplicacao::RateLimitUnit::ALL`] /
    /// [`caixa_core::render::PathShapeViolation::ALL`] /
    /// [`caixa_arch::invariants::InvariantKind::ALL`] /
    /// [`caixa_arch::report::ArchVerdict::ALL`] /
    /// [`caixa_lint::FixSafety::ALL`] / [`caixa_lint::Severity::ALL`]
    /// exhaustive-iteration surfaces — the thirteenth closed-set typed
    /// enum on the caixa surface (and the first inside `caixa-provedor`)
    /// to converge onto the same one-canonical-arm-list-per-enum
    /// discipline. Order matches variant declaration order verbatim
    /// (`Safe` → `Arena`).
    pub const ALL: &'static [Self] = &[Self::Safe, Self::Arena];

    /// Per-arm Go-import projection: the exact `rt "…"` line the
    /// ferrite-typed emit prepends inside its `import (…)` block. The
    /// canonical projection every ferrite-runtime-family consumer keys
    /// off — one typed dispatch on the substrate primitive replaces the
    /// pre-lift per-arm inline match at the two open-coded call sites
    /// [`crate::backend::emit_go_resource`] previously carried through
    /// the free-function [`ferrite_rt_import`] wrapper.
    #[must_use]
    pub const fn rt_import(self) -> &'static str {
        match self {
            Self::Safe => "rt \"github.com/pleme-io/ferrite/rt\"",
            Self::Arena => "rt \"github.com/pleme-io/ferrite/rt/arena\"",
        }
    }

    /// Short runtime-slug the emit-side burns into the generated
    /// file's header comment (`// Code generated by caixa-provedor
    /// (<variant-slug>). DO NOT EDIT.`). The canonical projection
    /// every ferrite-runtime-slug consumer keys off — one typed
    /// dispatch on the substrate primitive replaces the pre-lift
    /// per-arm inline match at [`crate::backend::emit_go_resource`]
    /// previously routed through the free-function
    /// [`ferrite_runtime_variant`] wrapper.
    #[must_use]
    pub const fn variant_slug(self) -> &'static str {
        match self {
            Self::Safe => "ferrite-safe",
            Self::Arena => "ferrite-arena",
        }
    }

    /// Reverse projection on the [`FerriteRuntime`] closed-set enum's
    /// canonical-slug axis — parses a `"ferrite-safe"` / `"ferrite-arena"`
    /// wire byte-string back to the typed enum, or returns `None` when
    /// `s` lies outside the two-arm accept-set [`Self::variant_slug`]
    /// emits. The single `&str → Self` projection every future re-entry
    /// point on the ferrite-runtime axis dispatches through (a future
    /// `feira publish-provider --runtime=<ferrite-safe|ferrite-arena>`
    /// CLI arg-parse that binds the wire byte-string into the typed
    /// enum before dispatching to the per-arm emitter, a future
    /// admission-webhook rejection body re-parsing a prior emission's
    /// header-comment slug back to the typed enum for policy-tier
    /// classification, a `tracing::field::Value::Str`-arm structured-
    /// log re-loader binding a prior `Display`-formatted output back
    /// to the typed enum for cross-run runtime-flavor histogram diff)
    /// would have had to re-inline a two-arm `match s` cascade that
    /// expressed no compile-time link back to the substrate primitive.
    ///
    /// Same closed-set-reverse-projection discipline the sibling
    /// [`caixa_core::CaixaKind::from_wire`] (2aa6d23) /
    /// [`caixa_core::CaixaDialeto::from_wire`] (d0e65ea) /
    /// [`caixa_core::supervisor::RestartStrategy::from_wire`] (4eec29c) /
    /// [`caixa_core::supervisor::RestartPolicy::from_wire`] (dd32ccf) /
    /// [`caixa_core::aplicacao::PlacementStrategy::from_wire`] (18c7342) /
    /// [`caixa_core::dep::DepList::from_wire`] (45ee563) /
    /// [`caixa_core::render::PathShapeViolation::from_wire`] (aebd9c6) /
    /// `caixa_arch::invariants::InvariantKind::from_wire` (b9e4e61) /
    /// `caixa_arch::report::ArchVerdict::from_wire` (6afe564) /
    /// `caixa_lint::diagnostic::Severity::from_wire` (5afff0e) /
    /// `caixa_lint::diagnostic::FixSafety::from_wire` (bd505a1) /
    /// `caixa_theme::style::Semantic::from_wire` (e7bca7b) typed enums
    /// carry on the peer wire-side `str → Self` axes — extends the
    /// substrate-wide `(as_str, from_wire)` round-trip family (here
    /// `(variant_slug, from_wire)`) onto the first `caixa-provedor`
    /// closed-set fieldless typed enum to converge on the reverse-
    /// projection discipline, matching the same two-way `str ↔ Self`
    /// round-trip every sibling closed-set enum already carries.
    /// Method-named `from_wire` (not `from_str`) to match the peer
    /// shapes verbatim and side-step a `clippy::should_implement_trait`
    /// lint that a plain `from_str` name would otherwise trigger
    /// without paired [`std::str::FromStr`] impl scaffolding this axis
    /// does not carry today. Returns `Option<Self>` (rather than
    /// `Result<Self, _>`) to match the peer shapes: the caller picks
    /// the diagnostic form appropriate for its use site (a future
    /// `feira publish-provider --runtime` CLI arg-parse renders its
    /// own per-verb error message; a future admission-webhook
    /// rejection body wraps the `None` outcome with the accepted-set
    /// enumeration `FerriteRuntime::ALL.iter().map(…)` for operator
    /// diagnostics).
    ///
    /// Pinned load-bearing at the substrate-primitive level by
    /// [`tests::ferrite_runtime_from_wire_accepts_every_variant_slug_output`]
    /// (round-trip witness against the peer [`Self::variant_slug`]
    /// axis) and
    /// [`tests::ferrite_runtime_from_wire_rejects_unknown_byte_strings`]
    /// (rejection witness against silent accept-set widening).
    #[must_use]
    pub fn from_wire(s: &str) -> Option<Self> {
        match s {
            "ferrite-safe" => Some(Self::Safe),
            "ferrite-arena" => Some(Self::Arena),
            _ => None,
        }
    }
}

/// Route the derived-style [`std::fmt::Display`] impl on
/// [`FerriteRuntime`] through the substrate-canonical
/// [`FerriteRuntime::variant_slug`] `pub const fn` accessor so every
/// consumer that binds a [`FerriteRuntime`] through the standard-
/// library `{}` formatting axis (a future `feira publish-provider`
/// per-runtime summary line, a `tracing::field::Value::Str`-arm
/// structured-log recorder on the emit path, any `format!("{runtime}")`
/// interpolation in a future emit-audit surface) reaches the same per-
/// arm kebab-case byte-string the pre-lift `variant_slug()` +
/// [`ferrite_runtime_variant`] free-function wrapper returns rather
/// than an open-coded per-arm match at every wire-up.
///
/// Follows the same closed-set-typed-enum `Display`-through-canonical-
/// projection convention the substrate-wide siblings
/// [`caixa_core::CaixaKind`] / [`caixa_core::CaixaDialeto`] /
/// [`caixa_core::aplicacao::PlacementStrategy`] /
/// [`caixa_core::aplicacao::RateLimitUnit`] /
/// [`caixa_core::supervisor::RestartStrategy`] /
/// [`caixa_core::supervisor::RestartPolicy`] /
/// [`caixa_core::dep::DepList`] / [`caixa_lint::Severity`] /
/// [`caixa_lint::FixSafety`] / [`caixa_arch::InvariantKind`] /
/// [`caixa_arch::ArchVerdict`] already carry through their paired
/// `as_str()` accessor, and the peer [`caixa_core::WitTarget`]
/// `Display`-through-`label()` route (aplicacao.rs:2427) carries on a
/// data-carrying typed enum whose canonical projection method is
/// domain-named rather than `as_str`. Extends the substrate-wide
/// closed-set-typed-enum `Display`-through-canonical-projection
/// discipline onto the caixa-provedor ferrite-runtime axis — the
/// first `caixa-provedor` closed-set typed enum to converge onto
/// the paired trait-impl half of the canonical projection triple.
///
/// The `variant_slug()` accessor is the canonical `&'static str` per-
/// arm projection on this enum (analog to `as_str()` on the sibling
/// caixa-core closed-set enums and `label()` on
/// [`caixa_core::WitTarget`]), returning `"ferrite-safe"` /
/// `"ferrite-arena"` — the same identity the file-header-comment
/// consumer at [`crate::backend::emit_go_resource`] burns into every
/// generated `// Code generated by caixa-provedor (<variant-slug>).
/// DO NOT EDIT.` prefix. Routing `Display` through it closes the
/// three-path convergence: `Debug` (the compiler-derived variant
/// name), `Display` (via `variant_slug`), and the emit-side header
/// slug all resolve to their canonical per-arm byte-string through
/// exactly one substrate-primitive dispatch per axis.
///
/// A future variant addition (a `Region` tier between [`Self::Safe`]
/// and [`Self::Arena`] for the intermediate `ferrite/rt/region`
/// checked-arena flavor the ferrite roadmap grows) reaches the
/// paired `Display` impl + [`AsRef<str>`] impl + every downstream
/// `.variant_slug()` consumer through one match-arm edit on
/// [`Self::variant_slug`] rather than a coordinated rewrite of every
/// open-coded per-arm match at every wire-up.
///
/// Pinned load-bearing by
/// [`tests::ferrite_runtime_display_and_as_ref_str_route_through_variant_slug_accessor`]
/// (three-path convergence pin: `Display`, `AsRef<str>`, and
/// `variant_slug` resolve to the same `&'static str` per arm) —
/// mirrors the peer `arch_verdict_display_and_as_ref_str_route_through_as_str_accessor`
/// (f3da79b) / `invariant_kind_display_and_as_ref_str_route_through_as_str_accessor`
/// (87c875a) / `fix_safety_display_and_as_ref_str_route_through_as_str_accessor`
/// (72782f7) pin shapes on the sibling caixa-arch / caixa-lint
/// closed-set-enum triple closures.
impl std::fmt::Display for FerriteRuntime {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.variant_slug())
    }
}

/// Route the standard-library [`AsRef<str>`] projection on
/// [`FerriteRuntime`] through the substrate-canonical
/// [`FerriteRuntime::variant_slug`] `pub const fn` accessor so every
/// consumer that binds a [`FerriteRuntime`] through the trait-
/// idiomatic `.as_ref()` (a future `HashMap::get::<str>(runtime.as_ref())`
/// per-runtime policy-table lookup, a `Command::arg` shell-out composing
/// the canonical runtime tag into a `feira publish-provider
/// --runtime=<tag>` filter, any `impl AsRef<str>`-bound generic
/// function) reaches the same per-arm kebab-case byte-string the
/// paired [`std::fmt::Display`] impl and the `variant_slug()` accessor
/// route through — one substrate-primitive dispatch per axis.
///
/// Peer of the substrate-wide sibling closed-set-enum
/// `AsRef<str>`-through-canonical-projection family — all ten
/// caixa-core / caixa-lint / caixa-arch closed-set fieldless typed
/// enums cited on the paired [`std::fmt::Display for FerriteRuntime`]
/// impl above. Rust-side newtype/typed-enum convention pairs
/// [`AsRef<str>`] and [`std::fmt::Display`] on the same primitive so
/// a caller who has one has both; before this lift,
/// [`FerriteRuntime`] carried neither trait impl even though its
/// canonical byte-string projection ([`Self::variant_slug`]) was
/// already established.
///
/// Pinned load-bearing on the same three-path convergence pin
/// [`tests::ferrite_runtime_display_and_as_ref_str_route_through_variant_slug_accessor`]
/// the sibling [`std::fmt::Display`] impl is pinned by — any future
/// silent detour that routes one impl through a divergent projection
/// (a per-arm inline `match self { … }` re-inlining that opens a
/// compile-time link to the un-lifted arm-literal, a swap onto the
/// sibling [`Self::rt_import`] Go-import projection that would
/// collide the runtime-slug axis with the import-line axis) trips at
/// caixa-provedor test time under `assert_eq!` rather than at a
/// downstream `impl AsRef<str>`-bound consumer's silent split.
impl AsRef<str> for FerriteRuntime {
    fn as_ref(&self) -> &str {
        self.variant_slug()
    }
}

/// Free-function wrapper preserved for the crate-level `pub use`
/// re-export in [`crate`]; routes through the substrate-primitive
/// method [`FerriteRuntime::rt_import`].
#[must_use]
pub fn ferrite_rt_import(runtime: FerriteRuntime) -> &'static str {
    runtime.rt_import()
}

/// Free-function wrapper preserved for the crate-level `pub use`
/// re-export in [`crate`]; routes through the substrate-primitive
/// method [`FerriteRuntime::variant_slug`].
#[must_use]
pub const fn ferrite_runtime_variant(runtime: FerriteRuntime) -> &'static str {
    runtime.variant_slug()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ferrite_runtime_all_lists_every_variant_in_declaration_order() {
        // Fail-before-pass-after pin on the [`gen_platform::IsVariant`]
        // derive's per-arm-list-per-enum discipline for
        // [`FerriteRuntime`]: any future variant addition (a `Region`
        // tier between [`FerriteRuntime::Safe`] and
        // [`FerriteRuntime::Arena`] for the intermediate
        // `ferrite/rt/region` checked-arena flavor the ferrite roadmap
        // grows) that lands the new variant on the enum without
        // extending [`FerriteRuntime::ALL`] trips this test — the
        // compiler-checked exhaustiveness on the paired
        // [`gen_platform::IsVariant`]-derived per-arm predicates
        // ([`FerriteRuntime::is_safe`] / [`FerriteRuntime::is_arena`])
        // covers the projection axis; this pin covers the
        // exhaustive-iteration axis so both halves of the closed-set
        // discipline migrate as one edit.
        assert_eq!(
            FerriteRuntime::ALL,
            &[FerriteRuntime::Safe, FerriteRuntime::Arena],
        );
        // Every arm satisfies exactly one of the paired per-arm
        // predicates — the byte-parity pin between the
        // [`FerriteRuntime::ALL`] iteration axis and the per-arm
        // [`gen_platform::IsVariant`]-derived predicate axis.
        for arm in FerriteRuntime::ALL {
            assert_eq!(
                usize::from(arm.is_safe()) + usize::from(arm.is_arena()),
                1,
                "FerriteRuntime::{arm:?} must satisfy exactly one of \
                 is_safe / is_arena",
            );
        }
    }

    #[test]
    fn ferrite_runtime_predicates_are_byte_equal_to_matches_family() {
        // Fail-before-pass-after pin on the two-arm convergence of the
        // pre-lift per-arm inline `match (runtime) { Safe => …, Arena
        // => … }` sites the two free-function projections
        // ([`ferrite_rt_import`], [`ferrite_runtime_variant`]) carried
        // onto the [`gen_platform::IsVariant`]-derive-generated per-arm
        // predicate family: for every arm, each predicate agrees
        // byte-for-byte with the pre-lift `matches!(_,
        // FerriteRuntime::…)` shape.
        //
        // A future rebrand touching either endpoint (a
        // `#[is_variant(name = "…")]` attribute drift on the derive, an
        // arm rename, an accidental peer predicate that shadows the
        // derive-generated one) would silently split the two paths and
        // trip this pin.
        for arm in FerriteRuntime::ALL {
            assert_eq!(
                arm.is_safe(),
                matches!(arm, FerriteRuntime::Safe),
                "FerriteRuntime::{arm:?}.is_safe() must agree with \
                 matches!(_, FerriteRuntime::Safe) byte-for-byte",
            );
            assert_eq!(
                arm.is_arena(),
                matches!(arm, FerriteRuntime::Arena),
                "FerriteRuntime::{arm:?}.is_arena() must agree with \
                 matches!(_, FerriteRuntime::Arena) byte-for-byte",
            );
        }
    }

    #[test]
    fn ferrite_runtime_projections_are_stable_per_arm_across_all() {
        // Accessor-level byte-parity pin: for every arm in
        // [`FerriteRuntime::ALL`], both projections
        // ([`FerriteRuntime::rt_import`] / [`FerriteRuntime::variant_slug`])
        // return the exact byte-string the pre-lift free-function form
        // ([`ferrite_rt_import`] / [`ferrite_runtime_variant`]) emitted.
        // This pin guards against a future silent split between the
        // free-function wrappers, the inherent-method projections, and
        // the two open-coded emit-side call sites in
        // [`crate::backend::emit_go_resource`] — any drift on the
        // canonical per-arm byte-string surfaces as a test failure
        // here rather than at downstream `go build` or `ferrite-check`
        // time.
        for arm in FerriteRuntime::ALL {
            assert_eq!(arm.rt_import(), ferrite_rt_import(*arm));
            assert_eq!(arm.variant_slug(), ferrite_runtime_variant(*arm));
        }
        // Pin the exact byte-shapes so a future rebrand of either the
        // `rt "…"` line or the header-comment slug surfaces here.
        assert_eq!(
            FerriteRuntime::Safe.rt_import(),
            "rt \"github.com/pleme-io/ferrite/rt\"",
        );
        assert_eq!(
            FerriteRuntime::Arena.rt_import(),
            "rt \"github.com/pleme-io/ferrite/rt/arena\"",
        );
        assert_eq!(FerriteRuntime::Safe.variant_slug(), "ferrite-safe");
        assert_eq!(FerriteRuntime::Arena.variant_slug(), "ferrite-arena");
    }

    #[test]
    fn ferrite_runtime_display_and_as_ref_str_route_through_variant_slug_accessor() {
        // Fail-before-pass-after three-path convergence pin: for every
        // arm in [`FerriteRuntime::ALL`], the paired
        // [`std::fmt::Display`] impl and [`AsRef<str>`] impl and the
        // substrate-canonical [`FerriteRuntime::variant_slug`] accessor
        // resolve to the same `&'static str` per arm. Mirrors the peer
        // `arch_verdict_display_and_as_ref_str_route_through_as_str_accessor`
        // (f3da79b) /
        // `invariant_kind_display_and_as_ref_str_route_through_as_str_accessor`
        // (87c875a) /
        // `fix_safety_display_and_as_ref_str_route_through_as_str_accessor`
        // (72782f7) pin shapes on the sibling caixa-arch / caixa-lint
        // closed-set-enum triple closures, extended onto the caixa-
        // provedor ferrite-runtime axis.
        //
        // Any future silent detour that routes one impl through a
        // divergent projection (a per-arm inline `match self { … }` re-
        // inlining that opens a compile-time link to the un-lifted arm-
        // literal, a swap onto the sibling [`FerriteRuntime::rt_import`]
        // Go-import projection that would collide the runtime-slug axis
        // with the import-line axis, an arm rename touching one impl but
        // not the paired sibling) trips at caixa-provedor test time
        // under `assert_eq!` rather than at a downstream `impl
        // AsRef<str>`-bound consumer's silent split or a `format!
        // ("{runtime}")` audit-line divergence.
        for arm in FerriteRuntime::ALL {
            let via_slug = arm.variant_slug();
            let via_display = format!("{arm}");
            let via_as_ref = <FerriteRuntime as AsRef<str>>::as_ref(arm);
            assert_eq!(
                via_display, via_slug,
                "FerriteRuntime::{arm:?} Display must byte-equal \
                 variant_slug() — got {via_display:?} vs {via_slug:?}",
            );
            assert_eq!(
                via_as_ref, via_slug,
                "FerriteRuntime::{arm:?} AsRef<str> must byte-equal \
                 variant_slug() — got {via_as_ref:?} vs {via_slug:?}",
            );
        }
        // Pin the exact per-arm byte-string on both trait impls so a
        // future rebrand of the canonical slug ("ferrite-safe" /
        // "ferrite-arena") surfaces at this pin rather than at a
        // downstream consumer's silent tag drift.
        assert_eq!(format!("{}", FerriteRuntime::Safe), "ferrite-safe");
        assert_eq!(format!("{}", FerriteRuntime::Arena), "ferrite-arena");
        assert_eq!(
            <FerriteRuntime as AsRef<str>>::as_ref(&FerriteRuntime::Safe),
            "ferrite-safe",
        );
        assert_eq!(
            <FerriteRuntime as AsRef<str>>::as_ref(&FerriteRuntime::Arena),
            "ferrite-arena",
        );
    }

    #[test]
    fn ferrite_runtime_from_wire_accepts_every_variant_slug_output() {
        // Fail-before-pass-after per-arm accept pin on the newly lifted
        // [`FerriteRuntime::from_wire`] reverse projection: every arm
        // in [`FerriteRuntime::ALL`] must parse back through `from_wire`
        // when fed its own [`FerriteRuntime::variant_slug`] output,
        // landing on `Some(same_variant)`. A regression that hand-rolled
        // either side's per-arm match without threading through the
        // shared two-string closed set would silently disagree on any
        // future arm rename (or a new arm the ferrite roadmap grows — a
        // `Region` tier between [`FerriteRuntime::Safe`] and
        // [`FerriteRuntime::Arena`] for the intermediate
        // `ferrite/rt/region` checked-arena flavor) and this pin flags
        // it at caixa-provedor build time rather than at a downstream
        // `feira publish-provider --runtime` consumer's silent tag
        // misclassification.
        //
        // Peer of the sibling
        // `caixa_theme::style::tests::semantic_from_wire_accepts_every_as_str_output`
        // (e7bca7b) /
        // `caixa_lint::diagnostic::tests::fix_safety_from_wire_accepts_every_as_str_output`
        // (bd505a1) /
        // `caixa_lint::diagnostic::tests::severity_from_wire_accepts_every_as_str_output`
        // (5afff0e) /
        // `caixa_arch::report::tests::arch_verdict_from_wire_accepts_every_as_str_output`
        // (6afe564) /
        // `caixa_arch::invariants::tests::invariant_kind_from_wire_accepts_every_as_str_output`
        // (b9e4e61) round-trip pins on the peer caixa-theme / caixa-lint
        // / caixa-arch closed-set-enum reverse-projection axes, and of
        // the sibling
        // `caixa_core::kind::tests::caixa_kind_wire_round_trips_through_from_wire`
        // (2aa6d23) /
        // `caixa_core::dialeto::tests::caixa_dialeto_from_wire_accepts_every_as_str_output`
        // (d0e65ea) /
        // `caixa_core::aplicacao::tests::placement_strategy_from_wire_accepts_every_lifted_constant`
        // (18c7342) /
        // `caixa_core::dep::tests::dep_list_round_trips_through_as_str_and_from_wire`
        // (45ee563) /
        // `caixa_core::render::tests::path_shape_violation_from_wire_accepts_every_as_str_output`
        // (aebd9c6) round-trip pins on the sibling caixa-core closed-
        // set typed-enum reverse-projection axes.
        for &variant in FerriteRuntime::ALL {
            let wire = variant.variant_slug();
            let parsed = FerriteRuntime::from_wire(wire).unwrap_or_else(|| {
                panic!(
                    "FerriteRuntime::from_wire({wire:?}) must accept \
                     every FerriteRuntime::variant_slug output — got \
                     None for the wire byte-string of {variant:?}"
                )
            });
            assert_eq!(
                parsed, variant,
                "FerriteRuntime::from_wire(FerriteRuntime::{variant:?}\
                 .variant_slug()) must return FerriteRuntime::{variant:?} \
                 — the (variant_slug, from_wire) pair must form a total \
                 round-trip on the closed two-arm FerriteRuntime arm-set",
            );
        }
    }

    #[test]
    fn ferrite_runtime_from_wire_rejects_unknown_byte_strings() {
        // Rejection pin on the [`FerriteRuntime::from_wire`] parser's
        // accept-set: any string outside the two-arm
        // [`FerriteRuntime::variant_slug`] output set must return
        // `None`. A future accidental widening of the accept-set (a
        // case-insensitive match that accepts `"FERRITE-SAFE"` /
        // `"Ferrite-Safe"`, a silent acceptance of the pre-lift
        // PascalCase Debug-derived shapes `"Safe"` / `"Arena"` on the
        // wire axis, a Levenshtein-forgiving arm-lookup that admits
        // `"ferrite-saf"` / `"arena"` typos, a silent absorption of the
        // sibling short-form `"safe"` / `"arena"` that the
        // caixa-lint `FixSafety::as_str` axis emits, a silent
        // absorption of the peer per-arm Go-import projection
        // [`FerriteRuntime::rt_import`] emits) would silently drift the
        // parser's accept-set from the emitter's — a downstream
        // provider-emit re-loader that bound a prior emission's
        // [`Self::variant_slug`] output back to the typed enum through
        // this parser would then bind a malformed byte-string to a
        // plausibly-wrong typed arm the caller does not route through
        // any fallback, silently misclassifying the reloaded row.
        //
        // Peer of the sibling
        // `caixa_theme::style::tests::semantic_from_wire_rejects_unknown_byte_strings`
        // (e7bca7b) /
        // `caixa_lint::diagnostic::tests::fix_safety_from_wire_rejects_unknown_byte_strings`
        // (bd505a1) /
        // `caixa_lint::diagnostic::tests::severity_from_wire_rejects_unknown_byte_strings`
        // (5afff0e) /
        // `caixa_arch::report::tests::arch_verdict_from_wire_rejects_unknown_byte_strings`
        // (6afe564) /
        // `caixa_arch::invariants::tests::invariant_kind_from_wire_rejects_unknown_byte_strings`
        // (b9e4e61) rejection pins on the peer caixa-theme / caixa-lint
        // / caixa-arch axes, and of the sibling
        // `caixa_kind_from_wire_rejects_unknown_byte_strings` (2aa6d23),
        // `caixa_dialeto_from_wire_rejects_unknown_byte_strings`
        // (d0e65ea),
        // `placement_strategy_from_wire_rejects_unknown_byte_strings`
        // (18c7342),
        // `dep_list_from_wire_returns_none_on_unknown_wire_scalar`
        // (45ee563), and
        // `path_shape_violation_from_wire_rejects_unknown_byte_strings`
        // (aebd9c6) rejection pins on the sibling caixa-core axes.
        for bad in [
            "",
            " ",
            "Safe",
            "SAFE",
            "safe",
            "Arena",
            "ARENA",
            "arena",
            "Ferrite-Safe",
            "FERRITE-SAFE",
            "Ferrite-Arena",
            "FERRITE-ARENA",
            "ferrite_safe",
            "ferrite_arena",
            "ferritesafe",
            "ferritearena",
            "ferrite-saf",
            "ferrite-aren",
            "region",
            "ferrite-region",
            "unsafe",
            "gc",
            "rt \"github.com/pleme-io/ferrite/rt\"",
            "rt \"github.com/pleme-io/ferrite/rt/arena\"",
            "ferrite-safe ",
            " ferrite-safe",
            "ferrite-safe\n",
            "ferrite-safe\t",
            "ferrite-arena ",
            " ferrite-arena",
        ] {
            assert!(
                FerriteRuntime::from_wire(bad).is_none(),
                "FerriteRuntime::from_wire({bad:?}) must return None — \
                 the parser's accept-set is exactly the two \
                 FerriteRuntime::variant_slug outputs; a widening would \
                 silently split the parser's accept-set from the \
                 emitter's arm-set",
            );
        }
    }

    #[test]
    fn ferrite_runtime_from_wire_round_trips_through_display_and_as_ref() {
        // Three-path convergence pin against the sibling
        // `(variant_slug, Display, AsRef<str>)` canonical-projection
        // triple: [`FerriteRuntime::from_wire`] must accept the byte-
        // string every path emits, so a caller that binds a prior
        // emission through any of the three paths and re-parses it
        // through the reverse projection reaches the same typed enum
        // by construction.
        //
        // A future silent detour that routes one of the three emitting
        // paths through a divergent projection (a per-arm inline
        // `match self { … }` re-inlining that opens a compile-time link
        // to the un-lifted arm-literal, a swap onto the sibling
        // [`FerriteRuntime::rt_import`] Go-import projection that would
        // collide the runtime-slug axis with the import-line axis)
        // would trip this pin under `assert_eq!` rather than at a
        // downstream re-loader's silent split.
        for &variant in FerriteRuntime::ALL {
            let via_slug = variant.variant_slug();
            let via_display = format!("{variant}");
            let via_as_ref = <FerriteRuntime as AsRef<str>>::as_ref(&variant).to_owned();
            assert_eq!(
                FerriteRuntime::from_wire(via_slug),
                Some(variant),
                "FerriteRuntime::from_wire(variant_slug) must return \
                 Some({variant:?})",
            );
            assert_eq!(
                FerriteRuntime::from_wire(&via_display),
                Some(variant),
                "FerriteRuntime::from_wire(Display) must return \
                 Some({variant:?})",
            );
            assert_eq!(
                FerriteRuntime::from_wire(&via_as_ref),
                Some(variant),
                "FerriteRuntime::from_wire(AsRef<str>) must return \
                 Some({variant:?})",
            );
        }
    }
}
