{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "caixa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "caixa.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "caixa.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
